import StatLean.ConcentrationInequalities

/-!
Throwaway axioms audit for the faithful infinite-T Dudley batch (to be
removed before merge). Expected on every line: `propext, Classical.choice,
Quot.sound` and NO `sorryAx`.
-/

open StatLean.ConcentrationInequalities

#print axioms StatLean.ConcentrationInequalities.coveringNumber_ne_top_of_totallyBounded
#print axioms StatLean.ConcentrationInequalities.totallyBounded_of_coveringNumber_ne_top
#print axioms StatLean.ConcentrationInequalities.residual_expectation_le
#print axioms StatLean.ConcentrationInequalities.residual_abs_expectation_le
#print axioms StatLean.ConcentrationInequalities.residual_tail_le
#print axioms StatLean.ConcentrationInequalities.discrete_dudley
#print axioms StatLean.ConcentrationInequalities.discrete_dudley_abs
#print axioms StatLean.ConcentrationInequalities.dudley_inequality
#print axioms StatLean.ConcentrationInequalities.dudley_inequality_abs
#print axioms StatLean.ConcentrationInequalities.dudley_inequality_abs_pair
#print axioms StatLean.ConcentrationInequalities.dudley_inequality_Ioi
#print axioms StatLean.ConcentrationInequalities.dudley_inequality_countable
#print axioms StatLean.ConcentrationInequalities.dudley_tail_three_term
#print axioms StatLean.ConcentrationInequalities.dudley_tail
#print axioms StatLean.ConcentrationInequalities.dudley_tail_three_term_countable
#print axioms StatLean.ConcentrationInequalities.generic_chaining_tail
#print axioms StatLean.ConcentrationInequalities.generic_chaining_of_admissible
#print axioms StatLean.ConcentrationInequalities.generic_chaining
#print axioms StatLean.ConcentrationInequalities.generic_chaining_real
#print axioms StatLean.ConcentrationInequalities.discrete_dudley_of_finite
#print axioms StatLean.ConcentrationInequalities.dudley_inequality_abs_of_finite
