import StatLean.PointEstimation.Sufficiency.Defs
import Mathlib.MeasureTheory.Measure.Decomposition.RadonNikodym

/-!
# The Halmos–Savage criterion: sufficiency ⟺ the densities factor through `T`

For a dominated family there is always a countable mixture `ν = ∑ᵢ cᵢ P_{θᵢ}` of members of
the family which is *equivalent* to the family: `ν(A) = 0` exactly when `P_θ(A) = 0` for
every `θ`. Relative to such a mixture, sufficiency of a statistic `T` has an entirely
analytic characterization: `T` is sufficient if and only if every member has a
Radon–Nikodym derivative with respect to `ν` that is a function of `T` alone,
$$ \frac{dP_\theta}{d\nu}(x) \;=\; g_\theta\bigl(T(x)\bigr) \qquad (\nu\text{-a.e.}). $$

* `rnDeriv_comp_of_isSufficient` — the forward direction;
* `isSufficient_of_rnDeriv_comp` — the converse;
* `isSufficient_iff_rnDeriv_comp` — the two combined.

**Reference.** Classical characterization of sufficiency for dominated families relative to
an equivalent countable mixture of members of the family.

**Proof formalization notes.**
* The mixture is passed as data (`θs`, `c`) together with the defining equation `hν`, rather
  than being existentially quantified: the *existence* of an equivalent mixture for a
  dominated family is a separate brick, and stating the criterion relative to a given mixture
  keeps this file independent of it. The Lean name for the mixture is `ν`; `λ` (the classical
  notation) is Lean's lambda binder and cannot be used as an identifier.
* The equivalence condition of the classical statement splits in two here. One half,
  "`ν(A) = 0` implies `P_θ(A) = 0`", is the explicit hypothesis `hdom : ∀ θ, P θ ≪ ν`; the
  other half, "`P_θ(A) = 0` for all `θ` implies `ν(A) = 0`", is automatic from `hν` because
  `ν` is a sum of members of the family. No positivity of the weights `c` is assumed: it is
  not needed, since `hdom` is required for *every* `θ`, not just for the `θᵢ` appearing in the
  mixture.
* The forward direction is the substantive one: it shows that a determination of
  `P_θ(A ∣ T = t)` that does not depend on `θ` is also a determination of `P_ν(A ∣ T = t)`,
  and then identifies `dP_θ/dν` on the σ-field generated by `T` with its extension to the
  full σ-field. The converse needs only that `ν` is a finite dominating measure with the
  factorized densities — the mixture structure is not used there — but the hypotheses are
  kept uniform across the three statements for a single usable interface.
* Densities are `ℝ≥0∞`-valued (`Measure.rnDeriv`), so no finiteness or positivity side
  conditions appear; the factorizing functions `g_θ` are required measurable, which is what
  downstream consumers (the factorization theorem, the regular-conditional theorem) need.

**Bibliographic comments.** This criterion, together with the equivalent-mixture device that
makes it possible, is due to P. R. Halmos and L. J. Savage ("Application of the
Radon–Nikodym theorem to the theory of sufficient statistics," *Ann. Math. Statist.* **20**
(1949), 225–241); it is the measure-theoretic form of the factorization criterion of
J. Neyman ("Sur un teorema concernente le cosiddette statistiche sufficienti," *Giorn. Ist.
Ital. Attuari* **6** (1935), 320–334) and of the notion of sufficiency introduced by
R. A. Fisher ("On the mathematical foundations of theoretical statistics," *Phil. Trans. R.
Soc. A* **222** (1922), 309–368). The decision-theoretic reading of the criterion is
developed by R. R. Bahadur ("Sufficiency and statistical decision functions," *Ann. Math.
Statist.* **25** (1954), 423–462).
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace StatLean.PointEstimation

variable {Θ 𝓧 S : Type*} [MeasurableSpace 𝓧] [MeasurableSpace S]

/-- **Halmos–Savage, forward direction.** If `T` is sufficient then, relative to an
equivalent countable mixture `ν` of members of the family, every member's density with
respect to `ν` is a measurable function of `T`. -/
theorem rnDeriv_comp_of_isSufficient (P : Θ → Measure 𝓧) [∀ θ, IsProbabilityMeasure (P θ)]
    {T : 𝓧 → S}
    -- LEAN-ONLY: measurability of the statistic
    (hT : Measurable T) {ι : Type*} [Countable ι]
    -- USER-INPUT: the countable mixture data `(θᵢ, cᵢ)` of the classical criterion
    (θs : ι → Θ) (c : ι → ℝ≥0∞) (ν : Measure 𝓧)
    -- USER-INPUT: `ν` is the mixture `∑ᵢ cᵢ P_{θᵢ}`; this half of the equivalence condition
    -- makes every `P_θ`-null set `ν`-null automatically
    (hν : ν = Measure.sum fun i => c i • P (θs i)) [IsFiniteMeasure ν]
    -- USER-INPUT: the other half of the equivalence condition: `ν` dominates the family
    (hdom : ∀ θ, P θ ≪ ν)
    -- USER-INPUT: sufficiency of `T` in the per-event sense
    (hsuf : IsSufficient P T) :
    ∀ θ, ∃ g : S → ℝ≥0∞, Measurable g ∧ (P θ).rnDeriv ν =ᵐ[ν] fun x => g (T x) := by
  sorry

/-- **Halmos–Savage, converse direction.** If every member's density with respect to the
equivalent mixture `ν` factors through `T`, then `T` is sufficient: the conditional
probability function of `ν` given `T` serves as a determination for every member. -/
theorem isSufficient_of_rnDeriv_comp (P : Θ → Measure 𝓧) [∀ θ, IsProbabilityMeasure (P θ)]
    {T : 𝓧 → S}
    -- LEAN-ONLY: measurability of the statistic
    (hT : Measurable T) {ι : Type*} [Countable ι]
    -- USER-INPUT: the countable mixture data `(θᵢ, cᵢ)` of the classical criterion
    (θs : ι → Θ) (c : ι → ℝ≥0∞) (ν : Measure 𝓧)
    -- USER-INPUT: `ν` is the mixture `∑ᵢ cᵢ P_{θᵢ}` (not used by this direction, kept for
    -- interface uniformity with the forward direction)
    (hν : ν = Measure.sum fun i => c i • P (θs i)) [IsFiniteMeasure ν]
    -- USER-INPUT: `ν` dominates the family
    (hdom : ∀ θ, P θ ≪ ν)
    -- USER-INPUT: the densities factor through `T`
    (hfac : ∀ θ, ∃ g : S → ℝ≥0∞, Measurable g ∧ (P θ).rnDeriv ν =ᵐ[ν] fun x => g (T x)) :
    IsSufficient P T := by
  sorry

/-- **Halmos–Savage criterion.** Relative to an equivalent countable mixture `ν` of members
of the family, `T` is sufficient if and only if every member's density with respect to `ν` is
a measurable function of `T`. -/
theorem isSufficient_iff_rnDeriv_comp (P : Θ → Measure 𝓧) [∀ θ, IsProbabilityMeasure (P θ)]
    {T : 𝓧 → S}
    -- LEAN-ONLY: measurability of the statistic
    (hT : Measurable T) {ι : Type*} [Countable ι]
    -- USER-INPUT: the countable mixture data `(θᵢ, cᵢ)` of the classical criterion
    (θs : ι → Θ) (c : ι → ℝ≥0∞) (ν : Measure 𝓧)
    -- USER-INPUT: `ν` is the mixture `∑ᵢ cᵢ P_{θᵢ}`
    (hν : ν = Measure.sum fun i => c i • P (θs i)) [IsFiniteMeasure ν]
    -- USER-INPUT: `ν` dominates the family
    (hdom : ∀ θ, P θ ≪ ν) :
    IsSufficient P T ↔
      ∀ θ, ∃ g : S → ℝ≥0∞, Measurable g ∧ (P θ).rnDeriv ν =ᵐ[ν] fun x => g (T x) := by
  sorry

end StatLean.PointEstimation
