import Mathlib.Probability.Kernel.Composition.MeasureCompProd
import Mathlib.Probability.Kernel.Composition.IntegralCompProd
import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic

/-!
# Conditional expectation under a composition-product measure (Doob-fibre form)

For a probability measure `Q : Measure 𝓨`, a Markov kernel `r : Kernel 𝓨 𝓓`, and
the composition-product `Q ⊗ₘ r` on `𝓨 × 𝓓`, the conditional expectation of an
integrable `f : 𝓨 × 𝓓 → ℝ` under the σ-algebra generated by the first coordinate
`Prod.fst` is the fibrewise kernel average `p ↦ ∫ δ, f (p.1, δ) ∂(r p.1)`.

This is the `compProd`-specialization of the abstract characterization
`MeasureTheory.ae_eq_condExp_of_forall_setIntegral_eq`: the candidate
`p ↦ ∫ δ, f (p.1, δ) ∂(r p.1)` is `comap Prod.fst`-measurable and matches `f` on
every `comap Prod.fst`-measurable rectangle by `Measure.setIntegral_compProd`, so
it is a version of the conditional expectation.

It is the measure-theoretic bridge feeding the CAR coarsening-score
identification (`Operators/CoarseningScoreIdentification.lean`, vdV §25.5.3
thm:25.40): the tower `E_{Q,R}(b(X) | Y = y) = ∫ b(M(y, δ)) r(δ | y) dν(δ)` is
this lemma applied to `f = b ∘ M`.

Headline declaration: `condExp_compProd_fst`.
-/

open MeasureTheory ProbabilityTheory
open scoped ENNReal

namespace AsymptoticStatistics.ForMathlib.CondExpCompProd

/-- *Conditional expectation under `Q ⊗ₘ r` given the first coordinate is the
fibrewise kernel average*.

For an integrable `f : 𝓨 × 𝓓 → ℝ`, the conditional expectation of `f` under the
sub-σ-algebra `comap Prod.fst` generated by the `𝓨`-coordinate equals, `Q ⊗ₘ r`-a.e.,
the fibre integral `p ↦ ∫ δ, f (p.1, δ) ∂(r p.1)`.

The candidate is `comap Prod.fst`-measurable
(a function of `p.1`) and integrable; on a rectangle `Prod.fst ⁻¹' s = s ×ˢ univ`
with `s` measurable in `𝓨`, `Measure.setIntegral_compProd` gives
`∫_{s×univ} f d(Q ⊗ₘ r) = ∫_s (∫ f(y, ·) d(r y)) dQ`, so the candidate satisfies
the defining set-integral identity; conclude with
`ae_eq_condExp_of_forall_setIntegral_eq`. -/
theorem condExp_compProd_fst {𝓨 𝓓 : Type*} [MeasurableSpace 𝓨] [MeasurableSpace 𝓓]
    (Q : Measure 𝓨) [IsProbabilityMeasure Q] (r : Kernel 𝓨 𝓓) [IsMarkovKernel r]
    -- The function `f` and its integrability are the external data.
    (f : 𝓨 × 𝓓 → ℝ) (hf : Integrable f (Q ⊗ₘ r)) :
    (Q ⊗ₘ r)[f | MeasurableSpace.comap Prod.fst ‹MeasurableSpace 𝓨›]
      =ᵐ[Q ⊗ₘ r] fun p => ∫ δ, f (p.1, δ) ∂(r p.1) := by
  classical
  -- The sub-σ-algebra generated by `Prod.fst` is below the product σ-algebra.
  have hm : MeasurableSpace.comap Prod.fst ‹MeasurableSpace 𝓨›
      ≤ (inferInstance : MeasurableSpace (𝓨 × 𝓓)) := measurable_fst.comap_le
  set g : 𝓨 × 𝓓 → ℝ := fun p => ∫ δ, f (p.1, δ) ∂(r p.1) with hg_def
  -- `Prod.fst` pushes `Q ⊗ₘ r` forward to `Q`.
  have hmp : MeasurePreserving Prod.fst (Q ⊗ₘ r) Q :=
    ⟨measurable_fst, Measure.fst_compProd Q r⟩
  -- The fibre integral `y ↦ ∫ δ, f (y, δ) ∂(r y)` is a.e. strongly measurable on `Q`.
  have hG_aesm : AEStronglyMeasurable (fun y => ∫ δ, f (y, δ) ∂(r y)) Q := by
    have hf' : AEStronglyMeasurable f
        ((Kernel.const Unit Q ⊗ₖ Kernel.prodMkLeft Unit r) ()) := hf.1
    simpa only [Kernel.const_apply, Kernel.prodMkLeft_apply]
      using hf'.integral_kernel_compProd
  -- ... and `Q`-integrable, dominated by the norm fibre integral.
  have hnorm_int : Integrable (fun y => ∫ δ, ‖f (y, δ)‖ ∂(r y)) Q :=
    ((Measure.integrable_compProd_iff hf.1).mp hf).2
  have hG_int : Integrable (fun y => ∫ δ, f (y, δ) ∂(r y)) Q :=
    hnorm_int.mono' hG_aesm
      (Filter.Eventually.of_forall fun _ => norm_integral_le_integral_norm _)
  -- `g = (fibre integral) ∘ Prod.fst`, hence `(Q ⊗ₘ r)`-integrable.
  have hg_int : Integrable g (Q ⊗ₘ r) := hmp.integrable_comp_of_integrable hG_int
  -- `g` is `comap Prod.fst`-a.e. strongly measurable (it factors through `Prod.fst`).
  have hgm : AEStronglyMeasurable[MeasurableSpace.comap Prod.fst ‹MeasurableSpace 𝓨›]
      g (Q ⊗ₘ r) := by
    refine ⟨hG_aesm.mk _ ∘ Prod.fst, ?_, ?_⟩
    · exact hG_aesm.stronglyMeasurable_mk.comp_measurable
        (measurable_iff_comap_le.mpr le_rfl)
    · exact hmp.quasiMeasurePreserving.ae_eq_comp hG_aesm.ae_eq_mk
  -- Defining set-integral identity: on `comap Prod.fst`-rectangles both sides agree.
  have hg_eq : ∀ s, MeasurableSet[MeasurableSpace.comap Prod.fst ‹MeasurableSpace 𝓨›] s →
      (Q ⊗ₘ r) s < ∞ → ∫ x in s, g x ∂(Q ⊗ₘ r) = ∫ x in s, f x ∂(Q ⊗ₘ r) := by
    intro s hs _
    obtain ⟨A, hA, rfl⟩ := hs
    rw [← Set.prod_univ,
        Measure.setIntegral_compProd hA MeasurableSet.univ hg_int.integrableOn,
        Measure.setIntegral_compProd hA MeasurableSet.univ hf.integrableOn]
    refine integral_congr_ae (Filter.Eventually.of_forall fun a => ?_)
    dsimp only
    rw [setIntegral_univ, setIntegral_univ,
        show (fun b => g (a, b)) = (fun _ : 𝓓 => ∫ δ, f (a, δ) ∂(r a)) from rfl,
        integral_const]
    simp
  exact (ae_eq_condExp_of_forall_setIntegral_eq hm hf
    (fun s _ _ => hg_int.integrableOn) hg_eq hgm).symm

end AsymptoticStatistics.ForMathlib.CondExpCompProd
