import Mathlib.MeasureTheory.Function.ConditionalExpectation.RadonNikodym

/-!
# σ-finiteness of a comap-trimmed measure from σ-finiteness of the pushforward

If the pushforward `μ.map g` of a measure `μ` under a measurable `g : 𝓧 → 𝓨` is
σ-finite, then the trim of `μ` to the sub-σ-algebra `comap g` generated by `g`
is σ-finite. Consequently, the coarsening QMD argument of vdV Lemma 25.34-I
can form the real conditional expectation `μ[· | comap M]` under the single
regularity hypothesis `[SigmaFinite (μ.map M)]`.

Main declaration: `sigmaFinite_trim_comap_of_sigmaFinite_map`.
-/

open MeasureTheory

namespace AsymptoticStatistics.ForMathlib.SigmaFiniteTrimComap

/-- **σ-finiteness of the comap-trim from σ-finiteness of the pushforward.**
For a measurable `g : 𝓧 → 𝓨`, if `μ.map g` is σ-finite then `μ.trim g.comap_le`
is σ-finite. -/
theorem sigmaFinite_trim_comap_of_sigmaFinite_map
    {𝓧 𝓨 : Type*} {m𝓧 : MeasurableSpace 𝓧} {m𝓨 : MeasurableSpace 𝓨}
    (μ : Measure 𝓧) {g : 𝓧 → 𝓨} (hg : Measurable g)
    [hσ : SigmaFinite (μ.map g)] :
    SigmaFinite (μ.trim hg.comap_le) := by
  rw [← map_trim_comap hg] at hσ
  refine SigmaFinite.of_map (μ.trim hg.comap_le) ?_ hσ
  refine Measurable.aemeasurable ?_
  exact measurable_iff_comap_le.mpr le_rfl

end AsymptoticStatistics.ForMathlib.SigmaFiniteTrimComap
