import StatLean.NonparametricStatistics.RKHS

/-! Temporary axiom sweep for the RKHS batch — removed after the audit. -/

open StatLean.NonparametricStatistics

#print axioms StatLean.NonparametricStatistics.inner_kernelFun
#print axioms StatLean.NonparametricStatistics.norm_evalCLM
#print axioms StatLean.NonparametricStatistics.isKernelFun_scalarKernel
#print axioms StatLean.NonparametricStatistics.gramian_posDef_iff_linearIndependent
#print axioms StatLean.NonparametricStatistics.hasSum_scalarKernel
#print axioms StatLean.NonparametricStatistics.scalarKernel_submodule
#print axioms StatLean.NonparametricStatistics.continuous_coe_of_continuous_scalarKernel
#print axioms StatLean.NonparametricStatistics.IsParsevalFrame.hasSum_reconstruction
#print axioms StatLean.NonparametricStatistics.IsParsevalFrame.exists_dilation
#print axioms StatLean.NonparametricStatistics.isParsevalFrame_iff_hasSum_scalarKernel
#print axioms StatLean.NonparametricStatistics.scalarKernel_ofScalarKernel
#print axioms StatLean.NonparametricStatistics.IsKernelFun.exists_rkhs
#print axioms StatLean.NonparametricStatistics.exists_isometryEquiv_of_scalarKernel_eq
#print axioms StatLean.NonparametricStatistics.exists_unit_spanning_of_scalarKernel_rankOne
#print axioms StatLean.NonparametricStatistics.dualRKHS_scalarKernel
#print axioms StatLean.NonparametricStatistics.dualRKHS_range_coe
#print axioms StatLean.NonparametricStatistics.isKernelFun_min
#print axioms StatLean.NonparametricStatistics.rank_allOnesMatrix
#print axioms StatLean.NonparametricStatistics.sobolevH01_scalarKernel
#print axioms StatLean.NonparametricStatistics.sobolevH01_norm_kernelFun_sq
#print axioms StatLean.NonparametricStatistics.IsKernelFun.exists_featureMap
#print axioms StatLean.NonparametricStatistics.infDist_hyperplane
#print axioms StatLean.NonparametricStatistics.existsUnique_min_norm_marginFeasible
#print axioms StatLean.NonparametricStatistics.isMaxMarginHyperplane_of_min_norm
#print axioms StatLean.NonparametricStatistics.representer_mem_dataSpan
#print axioms StatLean.NonparametricStatistics.representer_existsUnique_of_convex
#print axioms StatLean.NonparametricStatistics.isKernelFun_boxProd_symbolAdjoint
#print axioms StatLean.NonparametricStatistics.rangeSpace_scalarKernel
#print axioms StatLean.NonparametricStatistics.rangeSpace_norm_eq_sInf
#print axioms StatLean.NonparametricStatistics.isPositive_mercerCLM
#print axioms StatLean.NonparametricStatistics.isMercerKernel_of_isPositive
#print axioms StatLean.NonparametricStatistics.tendstoUniformly_scalarKernel
#print axioms StatLean.NonparametricStatistics.isCompactOperator_mercerCLM
#print axioms StatLean.NonparametricStatistics.exists_mercerEigensystem
#print axioms StatLean.NonparametricStatistics.MercerEigensystem.hasSum_kernel
#print axioms StatLean.NonparametricStatistics.MercerEigensystem.tendstoUniformly_kernel
#print axioms StatLean.NonparametricStatistics.MercerEigensystem.hasSum_eigval
#print axioms StatLean.NonparametricStatistics.mercerCLM_comp_self
#print axioms StatLean.NonparametricStatistics.isMercerKernel_trace_smul_sub_boxProd
#print axioms StatLean.NonparametricStatistics.sqrtCLM_comp_self
#print axioms StatLean.NonparametricStatistics.range_integralOp_sqrtSymbol_eq
#print axioms StatLean.NonparametricStatistics.exists_orthonormalBasis_sqrt_eigfun
#print axioms StatLean.NonparametricStatistics.mem_range_coe_iff_summable
#print axioms StatLean.NonparametricStatistics.range_mercerCLM_subset
