import StatLean.NonparametricStatistics.RKHS.KernelFunction

/-!
# Moore's theorem: every kernel function generates an RKHS

Mathlib constructs, from a positive semidefinite operator-valued matrix
`K : Matrix X X (V →L[𝕜] V)`, a reproducing kernel Hilbert space `RKHS.OfKernel K`
whose kernel is `K` (`RKHS.kernel_ofKernel`).  This file specializes the construction to
scalar kernel functions `K : X → X → 𝕜`:

* `toCLMMatrix K` — the associated operator matrix `x y ↦ K x y • 1`;
* `IsKernelFun K ↔ (toCLMMatrix K).PosSemidef` — the scalar/operator bridge;
* `OfScalarKernel K` — the RKHS generated by a scalar kernel function;
* `scalarKernel_ofScalarKernel` — its reproducing kernel is `K` (Moore's theorem).

Together with `isKernelFun_scalarKernel` this gives the classical one-to-one
correspondence between kernel functions on `X` and RKHSs on `X`.

**Bibliographic comments.** E. H. Moore, *General Analysis, Part I*, Mem. Amer. Philos.
Soc. (1935); N. Aronszajn, Trans. Amer. Math. Soc. **68** (1950), Part I §2
(the "Moore–Aronszajn theorem").
-/

open RKHS ComplexConjugate
open scoped InnerProductSpace

namespace StatLean.NonparametricStatistics

variable {𝕜 : Type*} [RCLike 𝕜] {X : Type*}

variable (𝕜) in
/-- The operator-valued matrix `x y ↦ K x y • 1` associated to a scalar kernel
`K : X → X → 𝕜`.  Bridges scalar kernel functions to Mathlib's `RKHS.OfKernel`. -/
noncomputable def toCLMMatrix (K : X → X → 𝕜) : Matrix X X (𝕜 →L[𝕜] 𝕜) :=
  Matrix.of fun x y => K x y • (1 : 𝕜 →L[𝕜] 𝕜)

@[simp]
theorem toCLMMatrix_apply (K : X → X → 𝕜) (x y : X) (c : 𝕜) :
    toCLMMatrix 𝕜 K x y c = K x y * c := by
  simp [toCLMMatrix]

-- `c ↦ c • 1` is injective on `𝕜 →L[𝕜] 𝕜` (evaluate at `1`).
private theorem smul_one_inj {c d : 𝕜}
    (h : c • (1 : 𝕜 →L[𝕜] 𝕜) = d • (1 : 𝕜 →L[𝕜] 𝕜)) : c = d := by
  have := congrArg (fun T : 𝕜 →L[𝕜] 𝕜 => T 1) h
  simpa using this

-- The adjoint of a scalar multiple of the identity is the conjugate multiple.
private theorem star_smul_one (c : 𝕜) :
    star (c • (1 : 𝕜 →L[𝕜] 𝕜)) = conj c • (1 : 𝕜 →L[𝕜] 𝕜) := by
  rw [star_smul, star_one, RCLike.star_def]

-- Hermitian symmetry of `K` is exactly self-adjointness of the associated operator matrix.
private theorem toCLMMatrix_isHermitian_iff (K : X → X → 𝕜) :
    (toCLMMatrix 𝕜 K).IsHermitian ↔ ∀ x y, conj (K x y) = K y x := by
  constructor
  · intro h x y
    have h1 : star (toCLMMatrix 𝕜 K x y) = toCLMMatrix 𝕜 K y x := h.apply y x
    rw [show toCLMMatrix 𝕜 K x y = K x y • (1 : 𝕜 →L[𝕜] 𝕜) from rfl,
      show toCLMMatrix 𝕜 K y x = K y x • (1 : 𝕜 →L[𝕜] 𝕜) from rfl, star_smul_one] at h1
    exact smul_one_inj h1
  · intro h
    refine Matrix.ext fun x y => ?_
    change star (toCLMMatrix 𝕜 K y x) = toCLMMatrix 𝕜 K x y
    rw [show toCLMMatrix 𝕜 K y x = K y x • (1 : 𝕜 →L[𝕜] 𝕜) from rfl, star_smul_one, h]
    rfl

-- The quadratic-form entries of the operator matrix, in scalar terms.
private theorem inner_toCLMMatrix (K : X → X → 𝕜) (x y : X) (w w' : 𝕜) :
    ⟪toCLMMatrix 𝕜 K x y w, w'⟫_𝕜 = w' * conj (K x y) * conj w := by
  rw [toCLMMatrix_apply, RCLike.inner_apply, map_mul]
  ring

-- Merging repeated points: the quadratic form of a family `xs` with coefficients `a`
-- equals the quadratic form over the (distinct) image points with merged coefficients.
private theorem sum_fiberwise_quadratic [DecidableEq X] {n : ℕ} (K : X → X → 𝕜)
    (xs : Fin n → X) (a : Fin n → 𝕜) (t : Finset X) (ht : ∀ i, xs i ∈ t) :
    (∑ y ∈ t, ∑ y' ∈ t,
        conj (∑ i ∈ Finset.univ.filter fun i => xs i = y, a i)
          * (∑ j ∈ Finset.univ.filter fun j => xs j = y', a j) * K y y')
      = ∑ i, ∑ j, conj (a i) * a j * K (xs i) (xs j) := by
  have hmaps : ∀ i ∈ (Finset.univ : Finset (Fin n)), xs i ∈ t := fun i _ => ht i
  have step : ∀ y ∈ t,
      (∑ y' ∈ t, conj (∑ i ∈ Finset.univ.filter fun i => xs i = y, a i)
          * (∑ j ∈ Finset.univ.filter fun j => xs j = y', a j) * K y y')
        = ∑ i ∈ Finset.univ.filter fun i => xs i = y,
            ∑ j, conj (a i) * a j * K (xs i) (xs j) := by
    intro y _
    have e1 : ∀ y' ∈ t,
        conj (∑ i ∈ Finset.univ.filter fun i => xs i = y, a i)
            * (∑ j ∈ Finset.univ.filter fun j => xs j = y', a j) * K y y'
          = ∑ i ∈ Finset.univ.filter fun i => xs i = y,
              ∑ j ∈ Finset.univ.filter fun j => xs j = y',
                conj (a i) * a j * K (xs i) (xs j) := by
      intro y' _
      rw [map_sum, Finset.sum_mul, Finset.sum_mul]
      refine Finset.sum_congr rfl fun i hi => ?_
      rw [Finset.mul_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun j hj => ?_
      rw [(Finset.mem_filter.mp hi).2, (Finset.mem_filter.mp hj).2]
    refine (Finset.sum_congr rfl e1).trans ?_
    rw [Finset.sum_comm]
    exact Finset.sum_congr rfl fun i _ => Finset.sum_fiberwise_of_maps_to hmaps _
  refine (Finset.sum_congr rfl step).trans ?_
  exact Finset.sum_fiberwise_of_maps_to hmaps _

/-- The scalar/operator positivity bridge: a scalar function is a kernel function iff its
associated operator matrix is positive semidefinite. -/
theorem isKernelFun_iff_posSemidef_toCLMMatrix (K : X → X → 𝕜) :
    IsKernelFun K ↔ (toCLMMatrix 𝕜 K).PosSemidef := by
  classical
  have tfae : (toCLMMatrix 𝕜 K).PosSemidef ↔
      ((toCLMMatrix 𝕜 K).IsHermitian ∧ ∀ vv : X →₀ 𝕜,
        0 ≤ RCLike.re (vv.sum fun x w => vv.sum fun x' w' =>
          ⟪toCLMMatrix 𝕜 K x' x w, w'⟫_𝕜)) :=
    (RKHS.posSemidef_tfae (K := toCLMMatrix 𝕜 K)).out 0 2
  rw [tfae]
  constructor
  · -- kernel function ⇒ positive semidefinite operator matrix
    intro hK
    refine ⟨(toCLMMatrix_isHermitian_iff K).mpr hK.conj_symm, fun vv => ?_⟩
    set s : Finset X := vv.support with hs
    -- transfer the `Finset`-indexed quadratic form to a `Fin`-indexed one
    have hone : ∀ G : X → 𝕜,
        (∑ i : Fin s.card, G ((s.equivFin.symm i : {a // a ∈ s}) : X)) = ∑ x ∈ s, G x := by
      intro G
      have h1 : (∑ i : Fin s.card, G ((s.equivFin.symm i : {a // a ∈ s}) : X))
          = ∑ x : {a // a ∈ s}, G (x : X) :=
        Fintype.sum_equiv s.equivFin.symm _ _ fun _ => rfl
      rw [h1]
      exact Finset.sum_attach s G
    have hsum : ∀ F : X → X → 𝕜,
        (∑ i : Fin s.card, ∑ j : Fin s.card,
            F ((s.equivFin.symm i : {a // a ∈ s}) : X) ((s.equivFin.symm j : {a // a ∈ s}) : X))
          = ∑ x ∈ s, ∑ x' ∈ s, F x x' := by
      intro F
      refine (hone fun x => ∑ j : Fin s.card,
        F x ((s.equivFin.symm j : {a // a ∈ s}) : X)).trans ?_
      exact Finset.sum_congr rfl fun x _ => hone (F x)
    have hquad := hK.re_sum_nonneg s.card
      (fun i => ((s.equivFin.symm i : {a // a ∈ s}) : X))
      (fun i => vv ((s.equivFin.symm i : {a // a ∈ s}) : X))
    rw [hsum fun x x' => conj (vv x) * vv x' * K x x'] at hquad
    refine le_of_le_of_eq hquad (congrArg RCLike.re ?_)
    simp only [Finsupp.sum, ← hs]
    refine Finset.sum_congr rfl fun x _ => Finset.sum_congr rfl fun x' _ => ?_
    rw [inner_toCLMMatrix, hK.conj_symm]
    ring
  · -- positive semidefinite operator matrix ⇒ kernel function
    rintro ⟨hherm, hpos⟩
    have hsym : ∀ x y, conj (K x y) = K y x := (toCLMMatrix_isHermitian_iff K).mp hherm
    refine ⟨hsym, fun n xs a => ?_⟩
    set t : Finset X := Finset.image xs Finset.univ with ht
    set b : X → 𝕜 := fun y => ∑ i ∈ Finset.univ.filter fun i => xs i = y, a i with hb
    have hmem : ∀ i, xs i ∈ t := fun i => Finset.mem_image_of_mem xs (Finset.mem_univ i)
    have hbt : ∀ y, b y ≠ 0 → y ∈ t := by
      intro y hy
      by_contra hyt
      refine hy ?_
      have hempty : (Finset.univ.filter fun i => xs i = y) = ∅ :=
        Finset.filter_eq_empty_iff.mpr fun i _ hxi => hyt (hxi ▸ hmem i)
      rw [hb]
      simp [hempty]
    set vv : X →₀ 𝕜 := Finsupp.onFinset t b hbt with hvvdef
    have hvv : ∀ y, vv y = b y := fun _ => rfl
    have hsupp : vv.support ⊆ t := Finsupp.support_onFinset_subset
    -- rewrite the two `Finsupp` sums as `Finset` sums over `t`
    have hinner : ∀ (y : X) (w : 𝕜),
        (vv.sum fun x' w' => ⟪toCLMMatrix 𝕜 K x' y w, w'⟫_𝕜)
          = ∑ y' ∈ t, ⟪toCLMMatrix 𝕜 K y' y w, b y'⟫_𝕜 := by
      intro y w
      rw [Finsupp.sum_of_support_subset vv hsupp _ fun i _ => inner_zero_right _]
      exact Finset.sum_congr rfl fun y' _ => by rw [hvv]
    have houter : (vv.sum fun x w => vv.sum fun x' w' => ⟪toCLMMatrix 𝕜 K x' x w, w'⟫_𝕜)
        = ∑ y ∈ t, ∑ y' ∈ t, ⟪toCLMMatrix 𝕜 K y' y (b y), b y'⟫_𝕜 := by
      rw [Finsupp.sum_of_support_subset vv hsupp _ fun i _ => by
        simp only [map_zero, inner_zero_left, Finsupp.sum_fun_zero]]
      exact Finset.sum_congr rfl fun y _ => by rw [hvv]; exact hinner y (b y)
    have hpos' := hpos vv
    rw [houter] at hpos'
    refine le_of_le_of_eq hpos' (congrArg RCLike.re ?_)
    have hstep : (∑ y ∈ t, ∑ y' ∈ t, ⟪toCLMMatrix 𝕜 K y' y (b y), b y'⟫_𝕜)
        = ∑ y ∈ t, ∑ y' ∈ t, conj (b y) * b y' * K y y' := by
      refine Finset.sum_congr rfl fun y _ => Finset.sum_congr rfl fun y' _ => ?_
      rw [inner_toCLMMatrix, hsym]
      ring
    rw [hstep, hb]
    exact sum_fiberwise_quadratic K xs a t hmem

/-- The `Fact`-level positivity instance feeding Mathlib's `OfKernel` machinery. -/
instance instFactPosSemidefToCLMMatrix (K : X → X → 𝕜) [hK : Fact (IsKernelFun K)] :
    Fact (toCLMMatrix 𝕜 K).PosSemidef :=
  ⟨(isKernelFun_iff_posSemidef_toCLMMatrix K).mp hK.out⟩

variable (𝕜) in
/-- **The RKHS generated by a scalar kernel function** (Moore's construction), as the
Mathlib completion-of-finitely-supported-families model.  Requires the positivity of the
kernel as a `Fact` instance so that the inner-product-space instances are found. -/
abbrev OfScalarKernel (K : X → X → 𝕜) [Fact (IsKernelFun K)] : Type _ :=
  RKHS.OfKernel (toCLMMatrix 𝕜 K)

/-- **Moore's theorem** (scalar form): the RKHS generated by a kernel function `K` has
reproducing kernel exactly `K`. -/
theorem scalarKernel_ofScalarKernel (K : X → X → 𝕜) [Fact (IsKernelFun K)] :
    scalarKernel (OfScalarKernel 𝕜 K) = K := by
  funext x y
  rw [scalarKernel_eq_kernel_one, RKHS.OfKernel.kernel_ofKernel, toCLMMatrix_apply, mul_one]

universe uK uX in
/-- Existence form of Moore's theorem: every kernel function is the reproducing kernel of
*some* RKHS, living in `Type (max uK uX)` — the universe of the Moore completion.  (The
universe cannot be arbitrary: a discrete kernel on a large `X` forces `X` to inject into
the witness `H`.) -/
theorem IsKernelFun.exists_rkhs {k : Type uK} [RCLike k] {Y : Type uX} {K : Y → Y → k}
    (hK : IsKernelFun K) :
    ∃ (H : Type (max uK uX)) (_ : NormedAddCommGroup H) (_ : InnerProductSpace k H)
      (_ : CompleteSpace H) (_ : RKHS k H Y k), scalarKernel H = K := by
  haveI : Fact (IsKernelFun K) := ⟨hK⟩
  exact ⟨OfScalarKernel k K, inferInstance, inferInstance, inferInstance, inferInstance,
    scalarKernel_ofScalarKernel K⟩

end StatLean.NonparametricStatistics
