import StatLean.NonparametricStatistics.RKHS.KernelFunction

/-!
# Moore's theorem: every kernel function generates an RKHS

Mathlib constructs, from a positive semidefinite operator-valued matrix
`K : Matrix X X (V →L[𝕜] V)`, a reproducing kernel Hilbert space `RKHS.OfKernel K`
whose kernel is `K` (`RKHS.kernel_ofKernel`).  This file specializes the construction to
scalar kernel functions `K : X → X → 𝕜`:

* `toCLMMatrix K` — the associated operator matrix `x y ↦ K x y • 1`;
* `IsKernelFun K ↔ (toCLMMatrix K).PosSemidef` — the scalar/operator bridge;
* `OfScalarKernel K` — the RKHS generated by a scalar kernel function;
* `scalarKernel_ofScalarKernel` — its reproducing kernel is `K` (Moore's theorem).

Together with `isKernelFun_scalarKernel` this gives the classical one-to-one
correspondence between kernel functions on `X` and RKHSs on `X`.

**Bibliographic comments.** E. H. Moore, *General Analysis, Part I*, Mem. Amer. Philos.
Soc. (1935); N. Aronszajn, Trans. Amer. Math. Soc. **68** (1950), Part I §2
(the "Moore–Aronszajn theorem").
-/

open RKHS ComplexConjugate
open scoped InnerProductSpace

namespace StatLean.NonparametricStatistics

variable {𝕜 : Type*} [RCLike 𝕜] {X : Type*}

variable (𝕜) in
/-- The operator-valued matrix `x y ↦ K x y • 1` associated to a scalar kernel
`K : X → X → 𝕜`.  Bridges scalar kernel functions to Mathlib's `RKHS.OfKernel`. -/
noncomputable def toCLMMatrix (K : X → X → 𝕜) : Matrix X X (𝕜 →L[𝕜] 𝕜) :=
  Matrix.of fun x y => K x y • (1 : 𝕜 →L[𝕜] 𝕜)

@[simp]
theorem toCLMMatrix_apply (K : X → X → 𝕜) (x y : X) (c : 𝕜) :
    toCLMMatrix 𝕜 K x y c = K x y * c := by
  sorry

/-- The scalar/operator positivity bridge: a scalar function is a kernel function iff its
associated operator matrix is positive semidefinite. -/
theorem isKernelFun_iff_posSemidef_toCLMMatrix (K : X → X → 𝕜) :
    IsKernelFun K ↔ (toCLMMatrix 𝕜 K).PosSemidef := by
  sorry

variable (𝕜) in
/-- **The RKHS generated by a scalar kernel function** (Moore's construction), as the
Mathlib completion-of-finitely-supported-families model.  Requires the positivity of the
kernel as a `Fact` instance so that the inner-product-space instances are found. -/
abbrev OfScalarKernel (K : X → X → 𝕜) [Fact (IsKernelFun K)] : Type _ :=
  RKHS.OfKernel (toCLMMatrix 𝕜 K)

/-- The `Fact`-level positivity instance feeding Mathlib's `OfKernel` machinery. -/
instance instFactPosSemidefToCLMMatrix (K : X → X → 𝕜) [hK : Fact (IsKernelFun K)] :
    Fact (toCLMMatrix 𝕜 K).PosSemidef :=
  ⟨(isKernelFun_iff_posSemidef_toCLMMatrix K).mp hK.out⟩

/-- **Moore's theorem** (scalar form): the RKHS generated by a kernel function `K` has
reproducing kernel exactly `K`. -/
theorem scalarKernel_ofScalarKernel (K : X → X → 𝕜) [Fact (IsKernelFun K)] :
    scalarKernel (OfScalarKernel 𝕜 K) = K := by
  sorry

/-- Existence form of Moore's theorem: every kernel function is the reproducing kernel of
*some* RKHS. -/
theorem IsKernelFun.exists_rkhs {K : X → X → 𝕜} (hK : IsKernelFun K) :
    ∃ (H : Type _) (_ : NormedAddCommGroup H) (_ : InnerProductSpace 𝕜 H)
      (_ : CompleteSpace H) (_ : RKHS 𝕜 H X 𝕜), scalarKernel H = K := by
  sorry

end StatLean.NonparametricStatistics
