import StatLean.HypothesisTesting.Randomization.Defs
import StatLean.HypothesisTesting.Invariance.Defs
import StatLean.HypothesisTesting.ForMathlib.GroupAverageMeasure
import Mathlib.Probability.ConditionalExpectation
import Mathlib.MeasureTheory.Integral.Bochner.Set

/-!
# The conditional law given the orbit is the randomization distribution

The orbits $\mathbf{G}^x = \{gx : g \in \mathbf{G}\}$ partition the sample space. Under the
randomization hypothesis the conditional distribution of the data given its own orbit is
**uniform on that orbit**, and this conditional law is the *same* for every null
distribution — which is exactly why a test calibrated conditionally on the orbit is
unconditionally exact.

Concretely, writing $\mathcal{G}$ for the $\sigma$-field generated by the orbit partition
and $M = |\mathbf{G}|$, for every real statistic $T$ and every Borel set $B$,
$$ P\{T(X) \in B \mid \mathcal{G}\} \;=\; M^{-1}\sum_{g \in \mathbf{G}}
   \mathbf{1}\{T(gX) \in B\} \qquad P\text{-a.s.} $$
Taking $B = (-\infty, t]$ identifies the right-hand side with the randomization
distribution $\hat R(t \mid x)$ of `Randomization/Defs`. In particular, when the $M$ orbit
values of $T$ are distinct, the uniform law on those $M$ values is a conditional
distribution of $T(X)$ given the orbit.

**Reference.** E.L. Lehmann and J.P. Romano, *Testing Statistical Hypotheses*, 4th ed.,
Springer Nature Switzerland AG, 2022 (ISBN 978-3-030-70577-0), Chapter 17 (Permutation and
Randomization Tests), §17.2 (Permutation and Randomization Tests), Theorem 17.2.2 (the
conditional law given the orbit is the randomization distribution). (`TSH4 §17.2 Thm 17.2.2`.)

**Proof formalization notes.**
* The orbit $\sigma$-field is realized here as `invariantSigmaAlgebra G`, the
  $\sigma$-algebra of measurable sets that are *invariant* under every group element. For
  a finite group this is exactly the $\sigma$-field generated by the orbit partition: a
  measurable set is a union of orbits iff each $g$ maps it onto itself. Working with the
  invariant sets directly avoids constructing the generated $\sigma$-field and makes the
  key step — that the orbit average is $\mathcal{G}$-measurable — immediate.
  `invariantSigmaAlgebra_le` records that it is coarser than the ambient structure, which
  is what `condExp` requires.
* The conditional-expectation identity is expected to be discharged through the sibling
  brick `StatLean.HypothesisTesting.ForMathlib.GroupAverageMeasure`, whose lemma
  `condExp_eq_orbitAverage` supplies the averaging step: the orbit average is invariant,
  hence $\mathcal{G}$-measurable, and it has the right integral over every invariant set
  because each `x ↦ g • x` preserves both `P` (randomization hypothesis) and every
  invariant set. That last point — `g • ·` maps an invariant set onto itself — is the
  book's first claim in the argument and is the reason no measurability of the partition
  itself is needed.
* Everything is stated for a *bounded* measurable integrand first; the set version and
  the randomization-distribution version are the specializations to indicators, which are
  bounded by `1`. Boundedness (rather than integrability) is the honest hypothesis: it is
  what the indicator application supplies and it makes the finite orbit average trivially
  integrable.
* Measurability of the action is an explicit hypothesis rather than a `MeasurableSMul`
  instance, matching `Randomization/ExactLevel`.

**Bibliographic comments.** The conditional-uniformity description of randomization tests
is due to E. L. Lehmann and C. Stein ("On the theory of some non-parametric hypotheses,"
*Ann. Math. Statist.* **20** (1949), 28–45), building on R. A. Fisher (*The Design of
Experiments*, Oliver & Boyd, Edinburgh, 1935) and E. J. G. Pitman ("Significance tests
which may be applied to samples from any populations," *J. R. Statist. Soc. Suppl.* **4**
(1937), 119–130). Sampling a random subgroup element rather than enumerating the group is
M. Dwass ("Modified randomization tests for nonparametric hypotheses," *Ann. Math.
Statist.* **28** (1957), 181–187).
-/

open MeasureTheory
open scoped ENNReal

namespace StatLean.HypothesisTesting

variable {G : Type*} [Group G] [Fintype G] {𝓧 : Type*} [m𝓧 : MeasurableSpace 𝓧]
  [MulAction G 𝓧]

/-! ### The orbit `σ`-field -/

/-- The **orbit `σ`-field**: measurable sets that are invariant under the whole group.
For a finite group acting on the sample space these are exactly the measurable unions of
orbits, i.e. the `σ`-field generated by the orbit partition. -/
def invariantSigmaAlgebra (G : Type*) [Group G] [MulAction G 𝓧] : MeasurableSpace 𝓧 where
  MeasurableSet' E := MeasurableSet E ∧ ∀ g : G, (fun x : 𝓧 => g • x) ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, by simp⟩
  measurableSet_compl E hE :=
    ⟨hE.1.compl, fun g => by rw [Set.preimage_compl, hE.2 g]⟩
  measurableSet_iUnion f hf :=
    ⟨MeasurableSet.iUnion fun i => (hf i).1, fun g => by
      rw [Set.preimage_iUnion]
      exact Set.iUnion_congr fun i => (hf i).2 g⟩

/-- The orbit `σ`-field is coarser than the ambient one — the hypothesis `condExp`
needs. -/
lemma invariantSigmaAlgebra_le : invariantSigmaAlgebra (𝓧 := 𝓧) G ≤ m𝓧 := by
  intro s hs
  exact hs.1

/-! ### Private helpers: the orbit average is invariant and reproduces integrals -/

/-- The orbit average is constant along orbits (reindex the sum by right multiplication). -/
private lemma orbitAverage_smul (f : 𝓧 → ℝ) (g : G) (x : 𝓧) :
    orbitAverage G f (g • x) = orbitAverage G f x := by
  unfold orbitAverage
  congr 1
  have hstep : ∀ h : G, f (h • (g • x)) = f ((h * g) • x) := fun h => by rw [mul_smul]
  simp_rw [hstep]
  exact Equiv.sum_comp (Equiv.mulRight g) (fun h => f (h • x))

/-- The orbit average of a measurable function is measurable. -/
private lemma measurable_orbitAverage {f : 𝓧 → ℝ} (hf : Measurable f)
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x)) :
    Measurable (orbitAverage G f) := by
  unfold orbitAverage
  exact (Finset.measurable_sum _ fun g _ => hf.comp (hsmul g)).const_mul _

/-- The orbit average is measurable for the invariant `σ`-algebra. -/
private lemma measurable_orbitAverage_invariant {f : 𝓧 → ℝ} (hf : Measurable f)
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x)) :
    Measurable[invariantSigmaAlgebra G] (orbitAverage G f) := by
  intro B hB
  refine ⟨(measurable_orbitAverage hf hsmul) hB, fun g => ?_⟩
  ext x
  simp only [Set.mem_preimage, orbitAverage_smul]

/-- The orbit average is bounded by the same bound as `f`. -/
private lemma abs_orbitAverage_le {f : 𝓧 → ℝ} {C : ℝ} (hfb : ∀ x, |f x| ≤ C) (x : 𝓧) :
    |orbitAverage G f x| ≤ C := by
  have hcard : 0 < Fintype.card G := Fintype.card_pos
  have hcardR : (0 : ℝ) < Fintype.card G := by exact_mod_cast hcard
  unfold orbitAverage
  rw [abs_mul, abs_of_nonneg (by positivity)]
  calc (Fintype.card G : ℝ)⁻¹ * |∑ g : G, f (g • x)|
      ≤ (Fintype.card G : ℝ)⁻¹ * ∑ g : G, |f (g • x)| :=
        mul_le_mul_of_nonneg_left (Finset.abs_sum_le_sum_abs _ _) (by positivity)
    _ ≤ (Fintype.card G : ℝ)⁻¹ * ∑ _g : G, C :=
        mul_le_mul_of_nonneg_left (Finset.sum_le_sum fun g _ => hfb (g • x)) (by positivity)
    _ = C := by
        rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, ← mul_assoc,
          inv_mul_cancel₀ hcardR.ne', one_mul]

/-- On an invariant set, translating the integrand by `g` preserves the set integral (change
of variables using invariance of both the set and the measure). -/
private lemma setIntegral_smul_eq (P : Measure 𝓧) (f : 𝓧 → ℝ) (hf : Measurable f)
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    (hrand : RandomizationHypothesis G P) {s : Set 𝓧} (hs : MeasurableSet s)
    (hsinv : ∀ g : G, (fun x : 𝓧 => g • x) ⁻¹' s = s) (g : G) :
    ∫ x in s, f (g • x) ∂P = ∫ x in s, f x ∂P := by
  rw [← integral_indicator hs, ← integral_indicator hs]
  have hind : s.indicator (fun y => f (g • y)) = fun y => s.indicator f (g • y) := by
    funext y
    have hmem : (g • y ∈ s) ↔ (y ∈ s) := by rw [← Set.mem_preimage, hsinv g]
    by_cases hy : y ∈ s
    · rw [Set.indicator_of_mem hy, Set.indicator_of_mem (hmem.mpr hy)]
    · rw [Set.indicator_of_notMem hy, Set.indicator_of_notMem (fun h => hy (hmem.mp h))]
  rw [hind]
  have h := integral_map (μ := P) (φ := fun x => g • x) (f := s.indicator f)
    (hsmul g).aemeasurable (hf.indicator hs).aestronglyMeasurable
  rw [hrand g] at h
  rw [← h]

/-! ### Conditioning on the orbit -/

/-- **Conditional expectation given the orbit is the orbit average.** Under the
randomization hypothesis, for every bounded measurable `f`,
$$ E[f(X) \mid \mathcal{G}] \;=\; |\mathbf{G}|^{-1} \sum_{g \in \mathbf{G}} f(gX)
   \qquad P\text{-a.s.} $$
The right-hand side is `orbitAverage`, the finite-group symmetrization of the invariance
theory. -/
theorem condExp_orbit_eq_orbitAverage (P : Measure 𝓧) [IsProbabilityMeasure P]
    (f : 𝓧 → ℝ)
    -- USER-INPUT: the integrand is measurable; user-supplied function
    (hf : Measurable f)
    {C : ℝ}
    -- USER-INPUT: the integrand is bounded; supplied by the indicator applications
    (hfb : ∀ x, |f x| ≤ C)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) :
    condExp (invariantSigmaAlgebra G) P f =ᵐ[P] orbitAverage G f := by
  have hcard : 0 < Fintype.card G := Fintype.card_pos
  have hcardR : (Fintype.card G : ℝ) ≠ 0 := by exact_mod_cast hcard.ne'
  haveI : SigmaFinite (P.trim (invariantSigmaAlgebra_le (𝓧 := 𝓧) (G := G))) := by
    haveI : IsFiniteMeasure (P.trim (invariantSigmaAlgebra_le (𝓧 := 𝓧) (G := G))) :=
      isFiniteMeasure_trim _
    infer_instance
  have hfint : Integrable f P := (integrable_const C).mono' hf.aestronglyMeasurable
    (ae_of_all P fun x => by rw [Real.norm_eq_abs]; exact hfb x)
  have hoaint : Integrable (orbitAverage G f) P :=
    (integrable_const C).mono' (measurable_orbitAverage hf hsmul).aestronglyMeasurable
      (ae_of_all P fun x => by rw [Real.norm_eq_abs]; exact abs_orbitAverage_le hfb x)
  have hfg_int : ∀ g : G, Integrable (fun x => f (g • x)) P := fun g =>
    (integrable_const C).mono' (hf.comp (hsmul g)).aestronglyMeasurable
      (ae_of_all P fun x => by rw [Real.norm_eq_abs]; exact hfb (g • x))
  refine (ae_eq_condExp_of_forall_setIntegral_eq (invariantSigmaAlgebra_le (𝓧 := 𝓧) (G := G))
    hfint (fun s _ _ => hoaint.integrableOn) (fun s hs_m _ => ?_) ?_).symm
  · obtain ⟨hs, hsinv⟩ := hs_m
    unfold orbitAverage
    rw [integral_const_mul, integral_finset_sum _ fun g _ => (hfg_int g).integrableOn]
    simp_rw [setIntegral_smul_eq P f hf hsmul hrand hs hsinv]
    rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, ← mul_assoc,
      inv_mul_cancel₀ hcardR, one_mul]
  · exact (measurable_orbitAverage_invariant hf hsmul).stronglyMeasurable.aestronglyMeasurable

/-- **The conditional law of a statistic given the orbit, set form.** For every Borel
set `B`,
$$ P\{T(X) \in B \mid \mathcal{G}\} \;=\; M^{-1}\sum_{g}\mathbf{1}\{T(gX) \in B\}
   \qquad P\text{-a.s.} $$
i.e. the conditional law of `T(X)` given the orbit is the uniform law on the `M` orbit
values `T(gx)` (counted with multiplicity; if those values are distinct it is literally
the uniform distribution on them). -/
theorem condExp_orbit_indicator (P : Measure 𝓧) [IsProbabilityMeasure P] (T : 𝓧 → ℝ)
    -- USER-INPUT: the test statistic is measurable; user-supplied statistic
    (hT : Measurable T)
    {B : Set ℝ}
    -- USER-INPUT: `B` is Borel; the event whose conditional probability is computed
    (hB : MeasurableSet B)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) :
    condExp (invariantSigmaAlgebra G) P ((T ⁻¹' B).indicator (fun _ => (1 : ℝ)))
      =ᵐ[P] fun x => (Fintype.card G : ℝ)⁻¹ *
        ∑ g : G, B.indicator (fun _ => (1 : ℝ)) (T (g • x)) := by
  have hfmeas : Measurable ((T ⁻¹' B).indicator (fun _ => (1 : ℝ))) :=
    measurable_const.indicator (hT hB)
  have hfb : ∀ x, |(T ⁻¹' B).indicator (fun _ => (1 : ℝ)) x| ≤ 1 := by
    classical
    intro x; rw [Set.indicator_apply]; split_ifs <;> simp
  have hmain := condExp_orbit_eq_orbitAverage P ((T ⁻¹' B).indicator (fun _ => (1 : ℝ)))
    hfmeas hfb hsmul hrand
  have heq : orbitAverage G ((T ⁻¹' B).indicator (fun _ => (1 : ℝ)))
      = fun x => (Fintype.card G : ℝ)⁻¹ *
        ∑ g : G, B.indicator (fun _ => (1 : ℝ)) (T (g • x)) := by
    funext x
    rfl
  exact heq ▸ hmain

/-- **The conditional law given the orbit *is* the randomization distribution.** Taking
`B = (-∞, t]` in the set form identifies the conditional c.d.f. of `T(X)` given the orbit
with `randDist`, the randomization distribution of `Randomization/Defs`. This is the
statement that the randomization test is calibrated against the correct conditional
law. -/
theorem randDist_eq_condExp_orbit (P : Measure 𝓧) [IsProbabilityMeasure P] (T : 𝓧 → ℝ)
    -- USER-INPUT: the test statistic is measurable; user-supplied statistic
    (hT : Measurable T)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) (t : ℝ) :
    condExp (invariantSigmaAlgebra G) P ((T ⁻¹' Set.Iic t).indicator (fun _ => (1 : ℝ)))
      =ᵐ[P] fun x => randDist G T x t := by
  have hmain := condExp_orbit_indicator P T hT (B := Set.Iic t) measurableSet_Iic hsmul hrand
  have heq : (fun x => (Fintype.card G : ℝ)⁻¹ *
        ∑ g : G, (Set.Iic t).indicator (fun _ => (1 : ℝ)) (T (g • x)))
      = fun x => randDist G T x t := by
    funext x
    rfl
  exact heq ▸ hmain

end StatLean.HypothesisTesting
