import StatLean.HypothesisTesting.Randomization.Defs
import StatLean.HypothesisTesting.Invariance.Defs
import StatLean.HypothesisTesting.ForMathlib.GroupAverageMeasure
import Mathlib.Probability.ConditionalExpectation

/-!
# The conditional law given the orbit is the randomization distribution

The orbits $\mathbf{G}^x = \{gx : g \in \mathbf{G}\}$ partition the sample space. Under the
randomization hypothesis the conditional distribution of the data given its own orbit is
**uniform on that orbit**, and this conditional law is the *same* for every null
distribution — which is exactly why a test calibrated conditionally on the orbit is
unconditionally exact.

Concretely, writing $\mathcal{G}$ for the $\sigma$-field generated by the orbit partition
and $M = |\mathbf{G}|$, for every real statistic $T$ and every Borel set $B$,
$$ P\{T(X) \in B \mid \mathcal{G}\} \;=\; M^{-1}\sum_{g \in \mathbf{G}}
   \mathbf{1}\{T(gX) \in B\} \qquad P\text{-a.s.} $$
Taking $B = (-\infty, t]$ identifies the right-hand side with the randomization
distribution $\hat R(t \mid x)$ of `Randomization/Defs`. In particular, when the $M$ orbit
values of $T$ are distinct, the uniform law on those $M$ values is a conditional
distribution of $T(X)$ given the orbit.

**Reference.** Classical randomization/permutation testing; original sources in the
bibliographic comments below.

**Proof formalization notes.**
* The orbit $\sigma$-field is realized here as `invariantSigmaAlgebra G`, the
  $\sigma$-algebra of measurable sets that are *invariant* under every group element. For
  a finite group this is exactly the $\sigma$-field generated by the orbit partition: a
  measurable set is a union of orbits iff each $g$ maps it onto itself. Working with the
  invariant sets directly avoids constructing the generated $\sigma$-field and makes the
  key step — that the orbit average is $\mathcal{G}$-measurable — immediate.
  `invariantSigmaAlgebra_le` records that it is coarser than the ambient structure, which
  is what `condExp` requires.
* The conditional-expectation identity is expected to be discharged through the sibling
  brick `StatLean.HypothesisTesting.ForMathlib.GroupAverageMeasure`, whose lemma
  `condExp_eq_orbitAverage` supplies the averaging step: the orbit average is invariant,
  hence $\mathcal{G}$-measurable, and it has the right integral over every invariant set
  because each `x ↦ g • x` preserves both `P` (randomization hypothesis) and every
  invariant set. That last point — `g • ·` maps an invariant set onto itself — is the
  book's first claim in the argument and is the reason no measurability of the partition
  itself is needed.
* Everything is stated for a *bounded* measurable integrand first; the set version and
  the randomization-distribution version are the specializations to indicators, which are
  bounded by `1`. Boundedness (rather than integrability) is the honest hypothesis: it is
  what the indicator application supplies and it makes the finite orbit average trivially
  integrable.
* Measurability of the action is an explicit hypothesis rather than a `MeasurableSMul`
  instance, matching `Randomization/ExactLevel`.

**Bibliographic comments.** The conditional-uniformity description of randomization tests
is due to E. L. Lehmann and C. Stein ("On the theory of some non-parametric hypotheses,"
*Ann. Math. Statist.* **20** (1949), 28–45), building on R. A. Fisher (*The Design of
Experiments*, Oliver & Boyd, Edinburgh, 1935) and E. J. G. Pitman ("Significance tests
which may be applied to samples from any populations," *J. R. Statist. Soc. Suppl.* **4**
(1937), 119–130). Sampling a random subgroup element rather than enumerating the group is
M. Dwass ("Modified randomization tests for nonparametric hypotheses," *Ann. Math.
Statist.* **28** (1957), 181–187).
-/

open MeasureTheory
open scoped ENNReal

namespace StatLean.HypothesisTesting

variable {G : Type*} [Group G] [Fintype G] {𝓧 : Type*} [m𝓧 : MeasurableSpace 𝓧]
  [MulAction G 𝓧]

/-! ### The orbit `σ`-field -/

/-- The **orbit `σ`-field**: measurable sets that are invariant under the whole group.
For a finite group acting on the sample space these are exactly the measurable unions of
orbits, i.e. the `σ`-field generated by the orbit partition. -/
def invariantSigmaAlgebra (G : Type*) [Group G] [MulAction G 𝓧] : MeasurableSpace 𝓧 where
  MeasurableSet' E := MeasurableSet E ∧ ∀ g : G, (fun x : 𝓧 => g • x) ⁻¹' E = E
  measurableSet_empty := ⟨MeasurableSet.empty, by simp⟩
  measurableSet_compl E hE :=
    ⟨hE.1.compl, fun g => by rw [Set.preimage_compl, hE.2 g]⟩
  measurableSet_iUnion f hf :=
    ⟨MeasurableSet.iUnion fun i => (hf i).1, fun g => by
      rw [Set.preimage_iUnion]
      exact Set.iUnion_congr fun i => (hf i).2 g⟩

/-- The orbit `σ`-field is coarser than the ambient one — the hypothesis `condExp`
needs. -/
lemma invariantSigmaAlgebra_le : invariantSigmaAlgebra (𝓧 := 𝓧) G ≤ m𝓧 := by
  intro s hs
  exact hs.1

/-! ### Conditioning on the orbit -/

/-- **Conditional expectation given the orbit is the orbit average.** Under the
randomization hypothesis, for every bounded measurable `f`,
$$ E[f(X) \mid \mathcal{G}] \;=\; |\mathbf{G}|^{-1} \sum_{g \in \mathbf{G}} f(gX)
   \qquad P\text{-a.s.} $$
The right-hand side is `orbitAverage`, the finite-group symmetrization of the invariance
theory. -/
theorem condExp_orbit_eq_orbitAverage (P : Measure 𝓧) [IsProbabilityMeasure P]
    (f : 𝓧 → ℝ)
    -- USER-INPUT: the integrand is measurable; user-supplied function
    (hf : Measurable f)
    {C : ℝ}
    -- USER-INPUT: the integrand is bounded; supplied by the indicator applications
    (hfb : ∀ x, |f x| ≤ C)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) :
    condExp (invariantSigmaAlgebra G) P f =ᵐ[P] orbitAverage G f := by
  sorry

/-- **The conditional law of a statistic given the orbit, set form.** For every Borel
set `B`,
$$ P\{T(X) \in B \mid \mathcal{G}\} \;=\; M^{-1}\sum_{g}\mathbf{1}\{T(gX) \in B\}
   \qquad P\text{-a.s.} $$
i.e. the conditional law of `T(X)` given the orbit is the uniform law on the `M` orbit
values `T(gx)` (counted with multiplicity; if those values are distinct it is literally
the uniform distribution on them). -/
theorem condExp_orbit_indicator (P : Measure 𝓧) [IsProbabilityMeasure P] (T : 𝓧 → ℝ)
    -- USER-INPUT: the test statistic is measurable; user-supplied statistic
    (hT : Measurable T)
    {B : Set ℝ}
    -- USER-INPUT: `B` is Borel; the event whose conditional probability is computed
    (hB : MeasurableSet B)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) :
    condExp (invariantSigmaAlgebra G) P ((T ⁻¹' B).indicator (fun _ => (1 : ℝ)))
      =ᵐ[P] fun x => (Fintype.card G : ℝ)⁻¹ *
        ∑ g : G, if T (g • x) ∈ B then (1 : ℝ) else 0 := by
  sorry

/-- **The conditional law given the orbit *is* the randomization distribution.** Taking
`B = (-∞, t]` in the set form identifies the conditional c.d.f. of `T(X)` given the orbit
with `randDist`, the randomization distribution of `Randomization/Defs`. This is the
statement that the randomization test is calibrated against the correct conditional
law. -/
theorem randDist_eq_condExp_orbit (P : Measure 𝓧) [IsProbabilityMeasure P] (T : 𝓧 → ℝ)
    -- USER-INPUT: the test statistic is measurable; user-supplied statistic
    (hT : Measurable T)
    -- USER-INPUT: the group acts measurably; the action is user-supplied data
    (hsmul : ∀ g : G, Measurable (fun x : 𝓧 => g • x))
    -- USER-INPUT: the null law is `G`-invariant; the randomization hypothesis
    (hrand : RandomizationHypothesis G P) (t : ℝ) :
    condExp (invariantSigmaAlgebra G) P ((T ⁻¹' Set.Iic t).indicator (fun _ => (1 : ℝ)))
      =ᵐ[P] fun x => randDist G T x t := by
  sorry

end StatLean.HypothesisTesting
