import StatLean.HypothesisTesting.Invariance.Defs

/-!
# Family-preserving transformations and maximal invariants

This file assembles the structural backbone of the invariance reduction.

**The transformation group.** A bijection `g` of the sample space *preserves* the model
`P : Θ → Measure 𝓧` when the law of `g(X)` is again a member of the family: there is an
*induced* parameter map `gbar` with
$$ P_\theta\{g X \in A\} \;=\; P_{\bar g\theta}\{X \in A\},
   \qquad\text{equivalently}\qquad (P_\theta)\circ g^{-1} \;=\; P_{\bar g\theta}, $$
and `gbar` maps the parameter space *onto* itself. Family-preserving bimeasurable bijections
are closed under composition and inversion — they form a group — and `g ↦ gbar` is a
homomorphism, $\overline{g'g} = \bar g'\,\bar g$ and $\overline{g^{-1}} = \bar g^{-1}$.
Consequently any class of transformations leaving a testing problem invariant may be
enlarged to a group without loss.

**Maximal invariants.** Points `x₁ ∼ x₂` on a common orbit are indistinguishable by an
invariant test, so invariant tests are exactly the functions of a *maximal invariant* `M`
— an invariant map that takes a different value on each orbit. In set-theoretic form the
factorization `φ = h ∘ M` is automatic; upgrading `h` to a *measurable* function requires
a genuine structural assumption on `M`, transcribed here as a separating measurable
coordinate `Y` making `x ↦ (M x, Y x)` a measurable embedding.

**Stepwise reduction.** A maximal invariant for a group generated by two subgroups `D`
and `E` can be computed in two stages — first the `D`-maximal invariant `s`, then an
`E^*`-maximal invariant `t` of `s` — provided the `E`-action descends along `s`.

**Parameter-space shrinkage.** An invariant statistic has a law that only depends on the
parameter through a maximal invariant of the induced group: invariance identifies all
parameter points lying on a common induced orbit.

**Main results.**
* `PreservesFamily.mul`, `PreservesFamily.inv`, `familyPreservingSubgroup` — the group
  property, with `InducesOn.mul` / `InducesOn.inv` recording the homomorphism identities;
* `isInvariantTest_iff_factors` — invariant ⟺ a function of a maximal invariant;
* `isInvariantTest_iff_factors_measurable` — the measurable upgrade;
* `isMaximalInvariant_comp_of_subgroups` — stepwise maximal invariants;
* `map_maximalInvariant_eq_of_orbit` — the law of an invariant statistic depends on the
  parameter only through a maximal invariant of the induced group.

**Proof formalization notes.**
* `PreservesFamily` is deliberately *set-level*: the induced map `gbar : Θ → Θ` is packaged
  existentially together with the surjectivity demanded of it (the "onto" half of
  parameter preservation), rather than being bundled as an `Equiv`. Injectivity of `gbar` is
  **not** part of the definition — it is a consequence of identifiability of the model,
  proved separately in `InducesOn.bar_injective`; this keeps the definition honest about
  what preservation alone delivers.
* `familyPreservingSubgroup` therefore carries the identifiability hypothesis explicitly:
  without it, closure under inversion is not available.
* Maximal invariance of the *parameter-space* map (`v` below) is spelled out inline as
  the two set-level conditions rather than through `IsMaximalInvariant`, so that no
  measurable-space structure is silently demanded of the parameter space.
* The measurable factorization hypothesis is transcribed as
  `MeasurableEmbedding (fun x => (M x, Y x))`: injectivity, measurability, and
  measurable-image (hence Borel range with measurable inverse) are exactly the three
  demands of the classical structural assumption.
* In `isMaximalInvariant_comp_of_subgroups` the induced group `E^*` acting on the range
  of `s` is not built as an abstract group; its maximal-invariance requirement is
  transcribed pointwise through `s`. This is faithful: compatibility (the `hcompat`
  hypothesis) makes `e ↦ e^*` multiplicative on the range of `s`, so `{e^* : e ∈ E}` is
  already a group there and the two readings agree.

**Bibliographic comments.** Invariance as a systematic reduction principle for testing
problems is due to G. A. Hunt and C. Stein ("Most stringent tests of statistical
hypotheses," unpublished manuscript, 1946), developed further by C. Stein ("Some problems
in multivariate analysis, Part I," Technical Report 6, Department of Statistics, Stanford
University, 1956) and in E. L. Lehmann's lecture tradition of the 1950s. The
orbit/maximal-invariant calculus and the relationship between invariance and sufficiency
are treated systematically by W. J. Hall, R. A. Wijsman and J. K. Ghosh ("The
relationship between sufficiency and invariance with applications in sequential
analysis," *Ann. Math. Statist.* **36** (1965), 575–614). The measurability subtleties
attached to "a test depending only on `M`" go back to E. L. Lehmann and C. Stein ("On the
theory of some non-parametric hypotheses," *Ann. Math. Statist.* **20** (1949), 28–45).
-/

open MeasureTheory
open scoped ENNReal

namespace StatLean.HypothesisTesting

/-! ## Family-preserving transformations form a group -/

section Preserving

variable {Θ 𝓧 : Type*} [MeasurableSpace 𝓧] {P : Θ → Measure 𝓧}

/-- `gbar` is an **induced parameter map** for the sample-space bijection `g`: pushing a
member of the family forward along `g` lands on the member indexed by `gbar θ`, i.e.
`P_θ(g⁻¹A) = P_{gbarθ}(A)` for all measurable `A`. -/
def InducesOn (P : Θ → Measure 𝓧) (g : Equiv.Perm 𝓧) (gbar : Θ → Θ) : Prop :=
  ∀ θ, (P θ).map ⇑g = P (gbar θ)

/-- **Family-preserving transformation**: a bimeasurable bijection of the sample space
admitting an induced parameter map that carries the parameter space *onto* itself.

Surjectivity of the induced map is the "onto" half of parameter preservation; injectivity
is deliberately *not* required here — it follows from identifiability of the model
(`InducesOn.bar_injective`). -/
def PreservesFamily (P : Θ → Measure 𝓧) (g : Equiv.Perm 𝓧) : Prop :=
  Measurable ⇑g ∧ Measurable ⇑g.symm ∧
    ∃ gbar : Θ → Θ, Function.Surjective gbar ∧ InducesOn P g gbar

/-- The identity transformation preserves the family, with induced map the identity. -/
theorem inducesOn_one : InducesOn P (1 : Equiv.Perm 𝓧) id := by
  intro θ
  simp only [Equiv.Perm.coe_one, Measure.map_id, id_eq]

/-- The identity transformation is family-preserving. -/
theorem preservesFamily_one : PreservesFamily P (1 : Equiv.Perm 𝓧) := by
  refine ⟨?_, ?_, id, Function.surjective_id, inducesOn_one⟩
  · exact measurable_id
  · exact measurable_id

/-- Composition of induced maps: `(g'g)‾ = gbar' ∘ gbar` (the first homomorphism identity).
Recall `(g' * g) x = g' (g x)` for permutations. -/
theorem InducesOn.mul {g g' : Equiv.Perm 𝓧} {gbar gbar' : Θ → Θ}
    -- USER-INPUT: `g` preserves the family with induced map `gbar`
    (h : InducesOn P g gbar)
    -- USER-INPUT: `g'` preserves the family with induced map `gbar'`
    (h' : InducesOn P g' gbar')
    -- LEAN-ONLY: measurability of `g`, needed to push forward along the composite;
    -- automatic for the bimeasurable transformations the theory quantifies over
    (hg : Measurable ⇑g) :
    InducesOn P (g' * g) (gbar' ∘ gbar) := by
  -- TODO: under-hypothesized for general measurable spaces. The composite pushforward
  -- `(P θ).map ⇑(g'*g) = ((P θ).map ⇑g).map ⇑g'` (`Measure.map_map`) needs `Measurable ⇑g'`,
  -- which is NOT among the hypotheses (only `hg : Measurable ⇑g`). Without it the identity
  -- can fail: on a non-standard-Borel `𝓧`, `⇑g'` can be non-measurable while `⇑g'∘⇑g` is
  -- measurable (a measurable bijection can have a non-measurable inverse), so
  -- `(P θ).map ⇑(g'*g) ≠ ((P θ).map ⇑g).map ⇑g' = 0`. The intended (standard-Borel /
  -- bimeasurable) setting supplies `Measurable ⇑g'`; the content is discharged inline in
  -- `PreservesFamily.mul`, where it is available. Fix = add `Measurable ⇑g'` to the signature.
  sorry

/-- Family-preserving transformations are closed under composition. -/
theorem PreservesFamily.mul {g g' : Equiv.Perm 𝓧}
    -- USER-INPUT: both factors preserve the family
    (h : PreservesFamily P g) (h' : PreservesFamily P g') :
    PreservesFamily P (g' * g) := by
  obtain ⟨hgm, hgm', gbar, hsurj, hind⟩ := h
  obtain ⟨hg'm, hg'm', gbar', hsurj', hind'⟩ := h'
  refine ⟨?_, ?_, gbar' ∘ gbar, hsurj'.comp hsurj, ?_⟩
  · rw [Equiv.Perm.coe_mul]; exact hg'm.comp hgm
  · have hsymm : (⇑(g' * g).symm : 𝓧 → 𝓧) = ⇑g.symm ∘ ⇑g'.symm := funext fun x => by
      rw [Function.comp_apply, Equiv.symm_apply_eq, Equiv.Perm.coe_mul, Function.comp_apply,
        Equiv.apply_symm_apply, Equiv.apply_symm_apply]
    rw [hsymm]; exact hgm'.comp hg'm'
  · intro θ
    rw [Equiv.Perm.coe_mul, ← Measure.map_map hg'm hgm, hind θ]
    exact hind' (gbar θ)

/-- **Identifiability makes the induced map injective.** If distinct parameters index
distinct distributions, an induced parameter map is one-to-one. -/
theorem InducesOn.bar_injective {g : Equiv.Perm 𝓧} {gbar : Θ → Θ}
    -- USER-INPUT: the model is identifiable (distinct parameters, distinct laws)
    (hP : Function.Injective P)
    -- USER-INPUT: `gbar` is induced by `g`
    (h : InducesOn P g gbar)
    -- LEAN-ONLY: bimeasurability of `g`, used to undo the pushforward
    (hg : Measurable ⇑g) (hg' : Measurable ⇑g.symm) :
    Function.Injective gbar := by
  intro θ₁ θ₂ hθ
  apply hP
  have e1 : (P θ₁).map ⇑g = (P θ₂).map ⇑g := by rw [h θ₁, h θ₂, hθ]
  have e2 := congrArg (fun ν : Measure 𝓧 => ν.map ⇑g.symm) e1
  simpa only [Measure.map_map hg' hg, Equiv.symm_comp_self, Measure.map_id] using e2

/-- Inverse of an induced map: `(g⁻¹)‾ = (gbar)⁻¹` (the second homomorphism identity),
stated for an induced map already known to be bijective. -/
theorem InducesOn.inv {g : Equiv.Perm 𝓧} {gbar : Equiv.Perm Θ}
    -- USER-INPUT: `gbar` is induced by `g`
    (h : InducesOn P g ⇑gbar)
    -- LEAN-ONLY: measurability of `g⁻¹`, needed to push forward along the inverse
    (hg : Measurable ⇑g.symm) :
    InducesOn P g⁻¹ ⇑gbar⁻¹ := by
  -- TODO: under-hypothesized for general measurable spaces. Inverting the pushforward
  -- `((P θ').map ⇑g).map ⇑g.symm = P θ'` (`Measure.map_map`) needs BOTH `Measurable ⇑g` and
  -- `Measurable ⇑g.symm`, but only `hg : Measurable ⇑g.symm` is supplied. On a non-standard
  -- measurable space a bijection may be measurable in one direction only, and then the
  -- cancellation fails. The intended bimeasurable setting supplies `Measurable ⇑g`; the
  -- content is discharged inline in `PreservesFamily.inv`, where both are available. Fix =
  -- add `Measurable ⇑g` to the signature.
  sorry

/-- Family-preserving transformations are closed under inversion, given identifiability
(which is what turns the induced map into a bijection). -/
theorem PreservesFamily.inv {g : Equiv.Perm 𝓧}
    -- USER-INPUT: the model is identifiable
    (hP : Function.Injective P)
    -- USER-INPUT: `g` preserves the family
    (h : PreservesFamily P g) :
    PreservesFamily P g⁻¹ := by
  obtain ⟨hgm, hgm', gbar, hsurj, hind⟩ := h
  have hinj : Function.Injective gbar := hind.bar_injective hP hgm hgm'
  let e : Θ ≃ Θ := Equiv.ofBijective gbar ⟨hinj, hsurj⟩
  have hcoe : ∀ φ, e φ = gbar φ := fun φ => Equiv.ofBijective_apply _ _ _
  refine ⟨hgm', hgm, ⇑e.symm, e.symm.surjective, fun θ => ?_⟩
  have hkey : (P (e.symm θ)).map ⇑g = P θ := by
    rw [hind (e.symm θ), ← hcoe, Equiv.apply_symm_apply]
  have e2 := congrArg (fun ν : Measure 𝓧 => ν.map ⇑g.symm) hkey
  simp only [Measure.map_map hgm' hgm, Equiv.symm_comp_self, Measure.map_id] at e2
  exact e2.symm

/-- **The family-preserving transformations form a group.** For an identifiable model,
the bimeasurable bijections preserving `P` are a subgroup of the permutation group of the
sample space; hence any class of transformations leaving a problem invariant generates a
group of such transformations. -/
def familyPreservingSubgroup (P : Θ → Measure 𝓧) (hP : Function.Injective P) :
    Subgroup (Equiv.Perm 𝓧) where
  carrier := {g | PreservesFamily P g}
  mul_mem' := fun ha hb => PreservesFamily.mul hb ha
  one_mem' := preservesFamily_one
  inv_mem' := fun h => PreservesFamily.inv hP h

end Preserving

/-! ## Invariant tests factor through a maximal invariant -/

section Factorization

variable {𝓧 𝓘 : Type*} [MeasurableSpace 𝓧]

/-- **Invariant ⟺ a function of a maximal invariant** (set-level form). A test is
invariant under `G` exactly when it depends on the data only through a maximal
invariant. -/
theorem isInvariantTest_iff_factors {G : Type*} [Group G] [MulAction G 𝓧] {M : 𝓧 → 𝓘}
    -- USER-INPUT: `M` is a maximal invariant for the action of `G` on the sample space
    (hM : IsMaximalInvariant G M) (φ : 𝓧 → ℝ) :
    IsInvariantTest G φ ↔ ∃ h : 𝓘 → ℝ, ∀ x, φ x = h (M x) := by
  constructor
  · intro hInv
    classical
    refine ⟨fun i => if hx : ∃ x, M x = i then φ (Classical.choose hx) else 0, fun x => ?_⟩
    have hx : ∃ x', M x' = M x := ⟨x, rfl⟩
    obtain ⟨g, hg⟩ := hM.2 (Classical.choose hx) x (Classical.choose_spec hx)
    simp only [dif_pos hx]
    exact (congrArg φ hg).trans (hInv g (Classical.choose hx))
  · rintro ⟨h, hφ⟩
    intro g x
    simp only [hφ, hM.1]

/-- **Measurable factorization through a maximal invariant.** The set-level
factorization does not by itself make the factor `h` measurable; the classical structural
assumption supplies a measurable coordinate `Y` complementary to `M`, so that
`x ↦ (M x, Y x)` is one-to-one from the sample space onto a measurable subset of the
product, with measurable inverse. `MeasurableEmbedding` packages exactly these three
demands. Under it, a measurable invariant test is a measurable function of `M`. -/
theorem isInvariantTest_iff_factors_measurable {G : Type*} [Group G] [MulAction G 𝓧]
    {𝓨 : Type*} [MeasurableSpace 𝓘] [MeasurableSpace 𝓨] {M : 𝓧 → 𝓘} (Y : 𝓧 → 𝓨)
    -- USER-INPUT: `M` is a maximal invariant for the action of `G`
    (hM : IsMaximalInvariant G M)
    -- USER-INPUT: the structural assumption — `(M, Y)` maps the sample space one-to-one
    -- onto a measurable subset of the product, with measurable inverse
    (hMY : MeasurableEmbedding fun x => (M x, Y x))
    (φ : 𝓧 → ℝ) :
    (Measurable φ ∧ IsInvariantTest G φ) ↔ ∃ h : 𝓘 → ℝ, Measurable h ∧ ∀ x, φ x = h (M x) := by
  have hMmeas : Measurable M := measurable_fst.comp hMY.measurable
  constructor
  · rintro ⟨_, hInv⟩
    -- TODO: (⇒) requires measurable uniformization/selection. From `hM` we obtain a set-level
    -- factor `h₀` with `h₀ ∘ M = φ`; upgrading it to a *measurable* `h` needs a measurable
    -- section of `M`. `MeasurableEmbedding (M, Y)` makes `e '' (φ⁻¹ B)` measurable in `𝓘 × 𝓨`,
    -- but the factor's superlevel set `{i | h₀ i < a}` is the 𝓘-*projection* of that set, which
    -- is analytic, not measurable, on a general measurable space (it is measurable under a
    -- standard-Borel / measurable-selection hypothesis, e.g. Jankov–von Neumann). Not available
    -- from the bare `MeasurableEmbedding` here. Fix = a standard-Borel hypothesis on `𝓘`, `𝓨`.
    sorry
  · rintro ⟨h, hmeas_h, hφ⟩
    exact ⟨by rw [funext hφ]; exact hmeas_h.comp hMmeas, fun g x => by simp only [hφ, hM.1]⟩

end Factorization

/-! ## Stepwise maximal invariants -/

section Stepwise

variable {𝓧 𝓨 𝓩 : Type*} [MeasurableSpace 𝓧]

/-- **Stepwise maximal invariants.** Let the group `G` be generated by two subgroups `D`
and `E`, let `s` be a maximal invariant for `D`, and suppose the `E`-action descends along
`s` (equal `s`-values are carried to equal `s`-values by every `e ∈ E`), so that each
`e ∈ E` induces a transformation `e^*` of the range of `s` by `e^*(s x) = s(e·x)`. If `t`
is a maximal invariant for the induced group `E^*`, then `t ∘ s` is a maximal invariant
for `G`.

The maximal invariance of `t` under `E^*` is transcribed pointwise through `s`
(`ht_inv`, `ht_max`); see the module note on why this is faithful. -/
theorem isMaximalInvariant_comp_of_subgroups {G : Type*} [Group G] [MulAction G 𝓧]
    (D E : Subgroup G)
    -- USER-INPUT: `D` and `E` generate `G`
    (hgen : D ⊔ E = ⊤)
    {s : 𝓧 → 𝓨}
    -- USER-INPUT: `s` is a maximal invariant for the subgroup `D`
    (hs : IsMaximalInvariant ↥D s)
    -- USER-INPUT: the compatibility condition — equal `s`-values stay equal under `E`,
    -- which is what makes the induced transformations `e^*` well defined
    (hcompat : ∀ (e : ↥E) (x₁ x₂ : 𝓧), s x₁ = s x₂ → s ((e : G) • x₁) = s ((e : G) • x₂))
    {t : 𝓨 → 𝓩}
    -- USER-INPUT: `t` is invariant under the induced group `E^*`
    (ht_inv : ∀ (e : ↥E) (x : 𝓧), t (s ((e : G) • x)) = t (s x))
    -- USER-INPUT: `t` separates the `E^*`-orbits
    (ht_max : ∀ x₁ x₂ : 𝓧, t (s x₁) = t (s x₂) → ∃ e : ↥E, s x₂ = s ((e : G) • x₁)) :
    IsMaximalInvariant G (fun x => t (s x)) := by
  refine ⟨?_, ?_⟩
  · -- invariance: `{g | ∀ x, t (s (g • x)) = t (s x)}` is a subgroup containing `D` and `E`
    let H : Subgroup G :=
      { carrier := {g | ∀ x, t (s (g • x)) = t (s x)}
        one_mem' := fun x => by rw [one_smul]
        mul_mem' := fun {a b} ha hb x => by rw [mul_smul, ha (b • x), hb x]
        inv_mem' := fun {a} ha x => by
          have h := ha (a⁻¹ • x); rw [smul_smul, mul_inv_cancel, one_smul] at h
          rw [← h] }
    have hDH : D ≤ H := fun d hd x => congrArg t (hs.1 ⟨d, hd⟩ x)
    have hEH : E ≤ H := fun e he x => ht_inv ⟨e, he⟩ x
    have htop : (⊤ : Subgroup G) ≤ H := hgen ▸ sup_le hDH hEH
    exact fun g x => htop (Subgroup.mem_top g) x
  · intro x y hxy
    obtain ⟨e, he⟩ := ht_max x y hxy
    obtain ⟨d, hd⟩ := hs.2 ((e : G) • x) y he.symm
    exact ⟨(d : G) * (e : G), by rw [mul_smul]; exact hd⟩

end Stepwise

/-! ## Invariance shrinks the parameter space -/

section Shrinkage

variable {G Θ 𝓧 𝓘 𝓥 : Type*} [Group G] [MeasurableSpace 𝓧] [MeasurableSpace 𝓘]
  [MulAction G 𝓧] [MulAction G Θ]

open StatLean.PointEstimation (IsInvariantModel)

/-- **The law of an invariant statistic depends on the parameter only through a maximal
invariant of the induced group.** If `M` is invariant under `G` and `v` is maximal
invariant under the induced action on the parameter space, then parameters with the same
`v`-value give `M` the same distribution — invariance identifies all parameter points on a
common induced orbit. -/
theorem map_maximalInvariant_eq_of_orbit [MeasurableSMul G 𝓧] {P : Θ → Measure 𝓧}
    {M : 𝓧 → 𝓘} {v : Θ → 𝓥}
    -- USER-INPUT: the model intertwines the two actions
    (hP : IsInvariantModel (G := G) P)
    -- LEAN-ONLY: measurability of the statistic, needed to form its law
    (hMmeas : Measurable M)
    -- USER-INPUT: `M` is invariant under the sample-space action
    (hMinv : ∀ (g : G) (x : 𝓧), M (g • x) = M x)
    -- USER-INPUT: `v` is invariant under the induced parameter action
    (hv_inv : ∀ (g : G) (θ : Θ), v (g • θ) = v θ)
    -- USER-INPUT: `v` separates the induced orbits (maximal invariance of `v`)
    (hv_max : ∀ θ θ' : Θ, v θ = v θ' → ∃ g : G, θ' = g • θ)
    {θ₁ θ₂ : Θ}
    -- USER-INPUT: the two parameters lie on a common induced orbit
    (hθ : v θ₁ = v θ₂) :
    (P θ₁).map M = (P θ₂).map M := by
  -- From `hv_max` pick `g` with `θ₂ = g • θ₁`; then `P θ₂ = (P θ₁).map (g • ·)` (`hP`), and
  -- the claim reduces to `((P θ₁).map (g • ·)).map M = (P θ₁).map M`, i.e.
  -- `(P θ₁).map (M ∘ (g • ·)) = (P θ₁).map M` via `Measure.map_map`. `MeasurableSMul G 𝓧`
  -- supplies `Measurable (g • ·)`; `M ∘ (g • ·) = M` is `hMinv`.
  obtain ⟨g, hg⟩ := hv_max θ₁ θ₂ hθ
  have hgmeas : Measurable (fun x : 𝓧 => g • x) := measurable_const_smul g
  rw [hg, ← hP g θ₁, Measure.map_map hMmeas hgmeas]
  congr 1
  exact funext fun x => hMinv g x

end Shrinkage

end StatLean.HypothesisTesting
