import Mathlib.MeasureTheory.Function.L2Space
import Mathlib.Probability.Moments.Covariance
import Mathlib.MeasureTheory.Constructions.Pi

/-!
# Time series — core data model (processes, stationarity, autocovariance)

A (real, discrete-time) **time series** is a family `X : ℤ → Ω → ℝ` of random variables on
a probability space, indexed by two-sided time (FY's backshift operator is defined for
`k = ±1, ±2, …`, which fixes the ambient index set as `ℤ`). This laptop-only `Defs` file
fixes the shared data model of the `TimeSeries` area:

* `shift`, `fdd` — time shift and finite-dimensional distributions;
* `IsStrictlyStationary` (FY Definition 2.2) — shift-invariance of all finite-dimensional
  distributions, stated over arbitrary finite time tuples (the book's consecutive-window
  form is the special case `t i = i + 1`; the equivalence is
  `isStrictlyStationary_iff_window` in `Process/Stationary.lean`);
* `IsStationary` (FY Definition 2.1 — the book's unqualified "stationary", i.e. weak /
  second-order stationarity) — `L²` marginals, constant mean, shift-invariant covariance;
* `acvf`, `acf` (FY Definition 2.5) — autocovariance and autocorrelation functions;
* `sigmaLE`, `sigmaGE`, `sigmaLT` — the σ-algebras `σ{X_s : s ≤ n}`, `σ{X_s : s ≥ n}`,
  `σ{X_s : s < n}` generated by segments of the process (consumed by the model
  definitions in `Models/Defs.lean` and the mixing coefficients in `Mixing/Defs.lean`).

**Reference.** J. Fan and Q. Yao, *Nonlinear Time Series: Nonparametric and Parametric
Methods*, Springer Series in Statistics, 2003 (ISBN 0-387-95170-9): §2.1.1, Definitions
2.1–2.2 (pp. 29–30); §2.2.1, Definition 2.5 (p. 39); §1.3.4 (backshift, p. 13).
(`FY §2.1.1 Def 2.1–2.2; §2.2.1 Def 2.5`.)

**Proof formalization notes.**
* `acvf X μ k := cov[X k, X 0; μ]` delegates to Mathlib's `ProbabilityTheory.covariance`;
  it agrees with `Cov(X_{t+k}, X_t)` for every anchor `t` only under `IsStationary`
  (lemma `IsStationary.cov_eq_acvf` in `Process/SecondOrder.lean`); for non-stationary
  `X` it is an anchored junk value.
* `acf X μ k := acvf X μ k / acvf X μ 0` is junk (`= 0`) when `acvf X μ 0 = 0` by Lean's
  division convention; ACF theorems carry the hypothesis `0 < acvf X μ 0`.
* `IsStationary` does not demand measurability of the maps `X t` (integrals and
  covariances are junk-total); measurability enters as explicit hypotheses where used.

**Bibliographic comments.** Weak stationarity is due to A. Ya. Khinchin
("Korrelationstheorie der stationären stochastischen Prozesse", *Math. Ann.* **109**
(1934), 604–615); strict stationarity and the systematic theory of stationary sequences
were developed by A. N. Kolmogorov and H. Wold (*A Study in the Analysis of Stationary
Time Series*, Almqvist & Wiksell, Uppsala, 1938). The autocovariance/autocorrelation
vocabulary is standard since G. U. Yule's autoregression papers (1927) and Wold.
-/

open MeasureTheory ProbabilityTheory
open scoped ProbabilityTheory

namespace StatLean.TimeSeries

variable {Ω : Type*}

/-- Time-`k` **shift** of a process: `shift X k` observes `X` displaced `k` steps forward,
`(shift X k) t = X (t + k)`. FY's backshift operator `B^k` (§1.3.4, two-sided `k`) is
`shift X (-k)` in this notation. -/
def shift (X : ℤ → Ω → ℝ) (k : ℤ) : ℤ → Ω → ℝ := fun t => X (t + k)

@[simp] lemma shift_apply (X : ℤ → Ω → ℝ) (k t : ℤ) : shift X k t = X (t + k) := rfl

variable [MeasurableSpace Ω]

/-- **Finite-dimensional distribution** of the process at the time tuple `t : Fin n → ℤ`:
the joint law of `(X (t 0), …, X (t (n-1)))` as a measure on `Fin n → ℝ`. Junk (the zero
measure) when the tuple map is not a.e.-measurable, by the `Measure.map` convention. -/
noncomputable def fdd (X : ℤ → Ω → ℝ) (μ : Measure Ω) {n : ℕ} (t : Fin n → ℤ) :
    Measure (Fin n → ℝ) :=
  μ.map fun ω i => X (t i) ω

/-- **Strict stationarity** (FY §2.1.1, Definition 2.2): all finite-dimensional
distributions are invariant under time shifts. Stated over arbitrary finite time tuples
`t : Fin n → ℤ`; the book's form — `(X_1, …, X_n) ≐ (X_{1+k}, …, X_{n+k})` for all
`n ≥ 1`, `k ∈ ℤ` — is the special case of consecutive tuples and is equivalent
(`Process/Stationary.lean`). -/
def IsStrictlyStationary (X : ℤ → Ω → ℝ) (μ : Measure Ω) : Prop :=
  ∀ (n : ℕ) (t : Fin n → ℤ) (k : ℤ),
    (μ.map fun ω (i : Fin n) => X (t i + k) ω) = μ.map fun ω (i : Fin n) => X (t i) ω

/-- **(Weak) stationarity** (FY §2.1.1, Definition 2.1 — the book's unqualified
"stationary"): finite second moments, constant mean, and a covariance between `X_{t+k}`
and `X_t` that depends only on the lag `k`. -/
structure IsStationary (X : ℤ → Ω → ℝ) (μ : Measure Ω) : Prop where
  /-- Constitutive (FY §2.1.1 Def 2.1): finite second moments, `E(X_t²) < ∞` for all `t`. -/
  memLp : ∀ t, MemLp (X t) 2 μ
  /-- Constitutive (FY §2.1.1 Def 2.1(i)): the mean function is constant in time. -/
  integral_eq : ∀ s t, ∫ ω, X s ω ∂μ = ∫ ω, X t ω ∂μ
  /-- Constitutive (FY §2.1.1 Def 2.1(ii)): `Cov(X_{t+k}, X_t)` does not depend on `t`. -/
  cov_shift : ∀ t k : ℤ, cov[X (t + k), X t; μ] = cov[X k, X 0; μ]

/-- **Autocovariance function** (FY §2.2.1, Definition 2.5): `γ(k) = Cov(X_{t+k}, X_t)`,
anchored at `t = 0`. Under `IsStationary` the anchor is immaterial
(`IsStationary.cov_eq_acvf`); otherwise this is a junk anchor value. -/
noncomputable def acvf (X : ℤ → Ω → ℝ) (μ : Measure Ω) (k : ℤ) : ℝ :=
  cov[X k, X 0; μ]

/-- **Autocorrelation function** (FY §2.2.1, Definition 2.5): `ρ(k) = γ(k)/γ(0)`.
Junk (`= 0`) when `γ(0) = 0`, by Lean's division-by-zero convention; ACF theorems carry
`0 < acvf X μ 0`. -/
noncomputable def acf (X : ℤ → Ω → ℝ) (μ : Measure Ω) (k : ℤ) : ℝ :=
  acvf X μ k / acvf X μ 0

/-- **Sample mean** of a finite data vector (FY eq. (2.23)'s `X̄_T`). -/
noncomputable def sampleMean {T : ℕ} (x : Fin T → ℝ) : ℝ :=
  (T : ℝ)⁻¹ * ∑ t, x t

/-- **Sample autocovariance** (FY §2.2.2, eq. (2.23)): divisor `1/T` (not `1/(T−k)`),
mean-corrected; junk `0` for lags `k ≥ T` (empty sum). Nonnegative-definiteness of the
divisor-`T` convention is `sampleACVF`-psd in `Process/SampleACF.lean`. -/
noncomputable def sampleACVF {T : ℕ} (x : Fin T → ℝ) (k : ℕ) : ℝ :=
  (T : ℝ)⁻¹ * ∑ t : Fin T, if h : (t : ℕ) + k < T then
    (x t - sampleMean x) * (x ⟨(t : ℕ) + k, h⟩ - sampleMean x) else 0

/-- **Sample autocorrelation** (FY eq. (2.23)): `ρ̂(k) = γ̂(k)/γ̂(0)`, junk when
`γ̂(0) = 0`. -/
noncomputable def sampleACF {T : ℕ} (x : Fin T → ℝ) (k : ℕ) : ℝ :=
  sampleACVF x k / sampleACVF x 0

/-- The σ-algebra `σ{X_s : s ≤ n}` generated by the process up to and including time `n`
(FY §2.6's `𝓕_{-∞}^n`). -/
@[reducible] noncomputable def sigmaLE (X : ℤ → Ω → ℝ) (n : ℤ) : MeasurableSpace Ω :=
  ⨆ s ∈ Set.Iic n, MeasurableSpace.comap (X s) inferInstance

/-- The σ-algebra `σ{X_s : s ≥ n}` generated by the process from time `n` onward
(FY §2.6's `𝓕_n^∞`). -/
@[reducible] noncomputable def sigmaGE (X : ℤ → Ω → ℝ) (n : ℤ) : MeasurableSpace Ω :=
  ⨆ s ∈ Set.Ici n, MeasurableSpace.comap (X s) inferInstance

/-- The σ-algebra `σ{X_s : s < n}` generated by the strict past of time `n` (used for the
"noise independent of the past" clauses of the nonlinear models, FY §4.2 Definition 4.2). -/
@[reducible] noncomputable def sigmaLT (X : ℤ → Ω → ℝ) (n : ℤ) : MeasurableSpace Ω :=
  ⨆ s ∈ Set.Iio n, MeasurableSpace.comap (X s) inferInstance

end StatLean.TimeSeries
