// Chapter (or lecture) titles for the main textbooks, used to render the
// reference-page dropdowns as a chapter-ordered table of contents. Titles are
// authored from each book's table of contents; a chapter absent from the map
// falls back to a bare "Chapter N".

/** Reference keys that get a chapter-ordered TOC (vs. a flat citing-results list). */
export const TEXTBOOK_KEYS = new Set([
  "ding2024",
  "fanyao2003",
  "shalev2014",
  "vdv1998",
  "lu-bda",
  "wainwright2019",
  "candes-stat300c",
  "vershynin2018",
  "robert2007",
  "gelman2014",
  "tsybakov2009",
  "paulsen-raghupathi2016",
  "lauritzen1996",
  "bkm2011",
  "lehmann-romano2022",
  "lehmann-casella1998",
  "gentle2002",
]);

export function isTextbook(key: string): boolean {
  return TEXTBOOK_KEYS.has(key);
}

/** The unit word for a book's top-level division ("Chapter" by default). */
const CHAPTER_WORD: Record<string, string> = {
  "candes-stat300c": "Lecture",
};

export function chapterWord(key: string): string {
  return CHAPTER_WORD[key] ?? "Chapter";
}

const CHAPTER_TITLES: Record<string, Record<number, string>> = {
  "ding2024": {
    1: "Correlation, Association, and the Yule–Simpson Paradox",
    2: "Potential Outcomes",
    3: "The Completely Randomized Experiment and the Fisher",
    4: "Neymanian Repeated Sampling Inference in Completely",
    5: "Stratification and Post-Stratification in Randomized Experiments",
    6: "Rerandomization and Regression Adjustment",
    7: "Matched-Pairs Experiment",
    8: "Unification of the Fisherian and Neymanian Inferences in",
    9: "Bridging Finite and Super Population Causal Inference",
    10: "Observational Studies, Selection Bias, and Nonparametric",
    11: "The Central Role of the Propensity Score in Observational",
    12: "The Doubly Robust or the Augmented Inverse Propensity",
    13: "The Average Causal Effect on the Treated Units and Other",
    14: "Using the Propensity Score in Regressions for Causal Effects",
    15: "Matching in Observational Studies",
    16: "Difficulties of Unconfoundedness in Observational Studies for",
    17: "E-Value: Evidence for Causation in Observational Studies",
    18: "Sensitivity Analysis for the Average Causal Effect with Unmeasured Confounding",
    19: "Rosenbaum-Style p-Values for Matched Observational Studies with Unmeasured Confounding",
    20: "Overlap in Observational Studies: Difficulties and Opportunities",
    21: "An Experimental Perspective of the Instrumental Variable",
    22: "Disentangle Mixture Distributions and Instrumental Variable Inequalities",
    23: "An Econometric Perspective of the Instrumental Variable",
    24: "Application of the Instrumental Variable Method: Fuzzy Regression Discontinuity",
    25: "Application of the Instrumental Variable Method: Mendelian",
    26: "Principal Stratification",
    27: "Mediation Analysis: Natural Direct and Indirect Effects",
    28: "Controlled Direct Effect",
    29: "Time-Varying Treatment and Confounding",
  },
  "fanyao2003": {
    1: "Introduction",
    2: "Characteristics of Time Series",
    3: "ARMA Modeling and Forecasting",
    4: "Parametric Nonlinear Time Series Models",
    5: "Nonparametric Density Estimation",
    6: "Smoothing in Time Series",
    7: "Spectral Density Estimation and Its Applications",
    8: "Nonparametric Models",
    9: "Model Validation",
    10: "Nonlinear Prediction",
  },
  "shalev2014": {
    2: "A Gentle Start",
    3: "A Formal Learning Model",
    4: "Learning via Uniform Convergence",
    6: "The VC-Dimension",
    13: "Regularization and Stability",
    26: "Rademacher Complexities",
    28: "Proof of the Fundamental Theorem of Learning Theory",
    31: "PAC-Bayes",
  },
  vdv1998: {
    2: "Stochastic Convergence",
    3: "Delta Method",
    4: "Moment Estimators",
    5: "M- and Z-Estimators",
    6: "Contiguity",
    7: "Local Asymptotic Normality",
    8: "Efficiency of Estimators",
    18: "Stochastic Convergence in Metric Spaces",
    19: "Empirical Processes",
    25: "Semiparametric Models",
  },
  "lehmann-romano2022": {
    3: "Uniformly Most Powerful Tests",
    4: "Unbiasedness: Theory and First Applications",
    6: "Invariance",
    11: "Basic Large-Sample Theory",
    12: "Extensions of the CLT to Sums of Dependent Random Variables",
    14: "Quadratic Mean Differentiable Families",
    16: "Testing Goodness of Fit",
    17: "Permutation and Randomization Tests",
    18: "Bootstrap and Subsampling Methods",
  },
  "lehmann-casella1998": {
    1: "Preparations",
    2: "Unbiasedness",
    3: "Equivariance",
  },
  "lu-bda": {
    4: "Sub-Gaussian Random Variables",
    5: "Sub-Exponential Random Variables",
    6: "Bernstein and Maximal Inequalities",
    7: "Ordinary Least Squares",
    8: "Compressed Sensing",
    9: "Restricted Isometry and Recovery",
    10: "The Lasso",
    12: "Convex Optimization",
    13: "Gradient Descent",
    14: "Proximal and Accelerated Methods",
    19: "Family-Wise Error Rate",
    20: "False Discovery Rate",
    21: "Knockoffs",
  },
  wainwright2019: {
    2: "Basic Tail and Concentration Bounds",
    4: "Uniform Laws of Large Numbers",
    5: "Metric Entropy and Its Uses",
    6: "Random Matrices and Covariance Estimation",
    7: "Sparse Linear Models in High Dimensions",
    9: "Decomposability and Restricted Strong Convexity",
    10: "Matrix Estimation with Rank Constraints",
    15: "Minimax Lower Bounds",
  },
  "candes-stat300c": {
    2: "Chi-Squared Goodness-of-Fit",
    3: "Kolmogorov–Smirnov Test",
    5: "False Discovery Rate",
    7: "Benjamini–Hochberg Procedure",
    9: "Order Statistics and Ranks",
    15: "E-values and Empirical Bayes",
    19: "Conformal Inference",
    20: "False Discovery Rate",
    21: "Knockoffs",
  },
  vershynin2018: {
    2: "Concentration of Sums of Independent Random Variables",
    3: "Random Vectors in High Dimensions",
    6: "Quadratic Forms, Symmetrization and Contraction",
    8: "Chaining",
  },
  robert2007: {
    1: "Introduction",
    2: "Decision-Theoretic Foundations",
    3: "From Prior Information to Prior Distributions",
    4: "Bayesian Point Estimation",
    5: "Tests and Confidence Regions",
    6: "Bayesian Calculations",
    7: "Model Choice",
    10: "Hierarchical and Empirical Bayes Extensions",
  },
  "gentle2002": {
    1: "Preliminaries",
    2: "Monte Carlo Methods for Inference",
    3: "Randomization and Data Partitioning",
    4: "Bootstrap Methods",
    5: "Tools for Identification of Structure in Data",
    6: "Estimation of Functions",
    7: "Graphical Methods in Computational Statistics",
    8: "Estimation of Probability Density Functions Using Parametric Models",
    9: "Nonparametric Estimation of Probability Density Functions",
    10: "Structure in Data",
    11: "Statistical Models of Dependencies",
  },
  "tsybakov2009": {
    1: "Nonparametric Estimators",
    2: "Lower Bounds on the Minimax Risk",
    3: "Asymptotic Efficiency and Adaptation",
  },
  "paulsen-raghupathi2016": {
    1: "Introduction",
    2: "Fundamental Results",
    3: "Interpolation and Approximation",
    4: "Cholesky and Schur",
    5: "Operations on Kernels",
    6: "Vector-Valued Spaces",
    7: "Power Series on Balls and Pull-Backs",
    8: "Statistics and Machine Learning",
    9: "Negative Definite Functions",
    10: "Positive Definite Functions on Groups",
    11: "Applications of RKHS to Integral Operators",
    12: "Stochastic Processes",
  },
  lauritzen1996: {
    1: "Introduction",
    2: "Graphs and Hypergraphs",
    3: "Conditional Independence and Markov Properties",
    4: "Contingency Tables",
    5: "Multivariate Normal Models",
    6: "Models for Mixed Data",
    7: "Further Topics",
  },
  bkm2011: {
    1: "Basic Ideas and Examples",
    2: "The General Linear Latent Variable Model",
    3: "The Normal Linear Factor Model",
    4: "Binary Data: Latent Trait Models",
    5: "Polytomous Data: Latent Trait Models",
    6: "Latent Class Models",
    7: "Models and Methods for Manifest Variables of Mixed Type",
    8: "Relationships Between Latent Variables",
    9: "Related Techniques for Investigating Dependency",
  },
  gelman2014: {
    1: "Probability and Inference",
    2: "Single-Parameter Models",
    3: "Introduction to Multiparameter Models",
    5: "Hierarchical Models",
    11: "Basics of Markov Chain Simulation",
  },
};

export function chapterTitle(key: string, ch: number): string | undefined {
  return CHAPTER_TITLES[key]?.[ch];
}
