import StatLean.Bayesian.ForMathlib.IIDSeqKernel
import Mathlib.Probability.Kernel.Posterior
import Mathlib.MeasureTheory.Constructions.Polish.Basic

/-!
# Doob consistency: the joint sequential experiment (data model)

Data model for vdV Theorem 10.10 (Doob's posterior consistency theorem). On the product
space `Ω := (ℕ → 𝓧) × Θ` (infinite data sequence first, matching the data-first orientation
of `condDistrib` and `posterior`), we record:

* `doobJoint K π` — the joint law of `(X₁, X₂, …, Θ̄)`: prior `π` on the parameter,
  conditionally iid data from `K θ`;
* `doobData n` — the first-`n`-observations statistic;
* `doobSigma n` — the σ-algebra generated by the first `n` observations (the filtration of
  the sequential experiment);
* `StronglyConsistentAt K π θ` — strong posterior consistency at `θ`: for
  `K θ`-iid-almost-every data sequence, the posterior mass of every `ε`-ball around `θ`
  tends to one.

The generality is: `𝓧` standard Borel, `Θ` Polish metric (metric balls state consistency;
standard-Borel structure feeds the posterior kernel and the Lusin–Souslin argument). This
covers vdV's setting (`𝓧` Euclidean-Borel, `Θ ⊂ ℝᵏ`).

**Reference.** A. W. van der Vaart, *Asymptotic Statistics*, Cambridge Series in Statistical
and Probabilistic Mathematics, Cambridge University Press, 1998, Chapter 10 (Bayes
Procedures), §10.4 (Consistency), p. 149 (the construction of `(X₁, X₂, …, Θ̄)` and the
definition of consistency).

**Proof formalization notes.** Laptop-only data model. vdV defines consistency via weak
convergence to `δ_θ`; the ball form used here is equivalent for point limits (portmanteau on
open balls plus monotonicity) and avoids weak convergence of random measures. The a.s. set
does not depend on `ε` (the quantifier `∀ ε` is inside `∀ᵐ`).
-/

open MeasureTheory ProbabilityTheory Filter Topology
open scoped ENNReal ProbabilityTheory

namespace StatLean.Bayesian

variable {Θ 𝓧 : Type*} [mΘ : MeasurableSpace Θ] [m𝓧 : MeasurableSpace 𝓧]

/-- **The joint law of data sequence and parameter** `(X₁, X₂, …, Θ̄)`: prior `π`,
conditionally iid observations from `K θ`; data-first orientation (matching `condDistrib`
and `posterior`). -/
noncomputable def doobJoint (K : Kernel Θ 𝓧) [IsMarkovKernel K] (π : Measure Θ)
    [IsFiniteMeasure π] : Measure ((ℕ → 𝓧) × Θ) :=
  (π ⊗ₘ iidSeqKernel K).map Prod.swap

/-- The first-`n`-observations statistic on the joint space. -/
def doobData (n : ℕ) (ω : (ℕ → 𝓧) × Θ) : Fin n → 𝓧 :=
  fun i => ω.1 i.val


/-- The σ-algebra of the first `n` observations — the sequential filtration of the joint
experiment (as a plain σ-algebra; the `Filtration` packaging is done at the point of use). -/
def doobSigma (n : ℕ) : MeasurableSpace ((ℕ → 𝓧) × Θ) :=
  MeasurableSpace.comap (doobData n) inferInstance



/-- **Strong posterior consistency at `θ`** (vdV §10.4, p. 149): for `K θ`-iid-almost-every
data sequence, the posterior mass of every `ε`-ball around `θ` tends to one. -/
def StronglyConsistentAt [MetricSpace Θ] [StandardBorelSpace Θ] [Nonempty Θ]
    (K : Kernel Θ 𝓧) [IsMarkovKernel K] (π : Measure Θ) [IsFiniteMeasure π] (θ : Θ) :
    Prop :=
  ∀ᵐ ω ∂(Measure.infinitePi fun _ : ℕ => K θ), ∀ ε : ℝ, 0 < ε →
    Tendsto (fun n => ((iidKernel K n)†π) (fun i : Fin n => ω i.val) (Metric.ball θ ε))
      atTop (𝓝 1)

end StatLean.Bayesian
