import StatLean.AsymptoticStatistics.StrictModel.EfficientScoreVec
import StatLean.AsymptoticStatistics.Core.PathwiseVec
import Mathlib.Analysis.Matrix.Order

/-! # Vector efficient scores from the selected paths of (25.26) -/

open MeasureTheory Filter Topology
open scoped InnerProductSpace ENNReal

namespace AsymptoticStatistics.StrictModel.EfficientScoreChosenPathsVec

open AsymptoticStatistics.Core.Hilbert
open AsymptoticStatistics.Core.EIFVec
open AsymptoticStatistics.StrictModel.EfficientScore
open AsymptoticStatistics.StrictModel.EfficientScoreVec

variable {Ω : Type*} [MeasurableSpace Ω]
variable {P : Measure Ω} [IsProbabilityMeasure P]
variable {d : ℕ}

/-- The coordinate basis of the vector parameter space. -/
noncomputable def coordinateBasis (j : Fin d) : EuclideanSpace ℝ (Fin d) :=
  EuclideanSpace.single j 1

/-- Literal vector selected-path data from vdV equation (25.26).

Constitutive: every vector parameter direction and nuisance score has one
selected QMD path with score `Sθ a + g` and functional quotient `a`.
The multivariate Gaussian location model with nuisance `{0}` is an example. -/
structure VectorPaths25_26
    (Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d)))
    (ψ : Measure Ω → EuclideanSpace ℝ (Fin d)) where
  nuisanceSet : Set ↥(L2ZeroMean P)
  nuisance_zero_mem : (0 : ↥(L2ZeroMean P)) ∈ nuisanceSet
  selectedPath : ∀ (_a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)), g ∈ nuisanceSet →
      AsymptoticStatistics.Core.QMDPath.QMDPath P
  score_eq : ∀ (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)) (hg : g ∈ nuisanceSet),
      (selectedPath a g hg).score = Sθ a + g
  quotient : ∀ (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)) (hg : g ∈ nuisanceSet),
      Tendsto (fun t : ℝ => t⁻¹ • (ψ ((selectedPath a g hg).curve t) - ψ P))
        (𝓝[≠] 0) (𝓝 a)

/-- Closed nuisance tangent generated by the selected nuisance scores. -/
noncomputable def VectorPaths25_26.nuisanceTangent
    {Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d))}
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ) : Submodule ℝ ↥(L2ZeroMean P) :=
  (Submodule.span ℝ paths.nuisanceSet).topologicalClosure

/-- Closed total tangent generated by all selected scores `Sθ a + g`. -/
noncomputable def VectorPaths25_26.totalTangent
    {Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d))}
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ) : Submodule ℝ ↥(L2ZeroMean P) :=
  (Submodule.span ℝ {s | ∃ (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)), g ∈ paths.nuisanceSet ∧ s = Sθ a + g}).topologicalClosure

/-- Every selected score belongs to the closed total tangent generated by
the selected score family. -/
theorem VectorPaths25_26.selectedScore_mem
    {Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d))}
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ) (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)) (hg : g ∈ paths.nuisanceSet) :
    Sθ a + g ∈ paths.totalTangent := by
  apply (Submodule.span ℝ _).le_topologicalClosure
  apply Submodule.subset_span
  exact ⟨a, g, hg, rfl⟩

/-- Vector chosen-path differentiability; the specification quantifies only
over the selected paths, never over all same-score QMD paths. -/
structure ChosenPathwiseDifferentiableAtVec
    {Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d))}
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ) where
  derivative : paths.totalTangent →L[ℝ] EuclideanSpace ℝ (Fin d)
  derivative_spec : ∀ (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)) (hg : g ∈ paths.nuisanceSet),
      Tendsto (fun t : ℝ => t⁻¹ • (ψ ((paths.selectedPath a g hg).curve t) - ψ P))
        (𝓝[≠] 0)
        (𝓝 (derivative ⟨Sθ a + g, paths.selectedScore_mem a g hg⟩))
  derivative_selectedScore : ∀ (a : EuclideanSpace ℝ (Fin d))
    (g : ↥(L2ZeroMean P)) (hg : g ∈ paths.nuisanceSet),
      derivative ⟨Sθ a + g, paths.selectedScore_mem a g hg⟩ = a

/-- The closed nuisance tangent has its canonical orthogonal projection. -/
@[reducible] noncomputable def nuisanceProjectionInstance
    {Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d))}
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ) :
    paths.nuisanceTangent.HasOrthogonalProjection := by
  letI : CompleteSpace ↥(L2ZeroMean P) :=
    (L2ZeroMean_isClosed P).completeSpace_coe
  change ((Submodule.span ℝ paths.nuisanceSet).topologicalClosure).HasOrthogonalProjection
  exact @Submodule.HasOrthogonalProjection.ofCompleteSpace ℝ _ inferInstance
    inferInstance inferInstance _ (Submodule.topologicalClosure.completeSpace _)

/-- Gram positive-semidefiniteness plus book-level nonsingularity upgrades
the efficient information matrix to positive definiteness. -/
theorem efficientInformation_posDef_of_isUnit_det
    (Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d)))
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ)
    (hdet : letI := nuisanceProjectionInstance paths
      IsUnit (efficientInformationMatrix Sθ paths.nuisanceTangent
        (coordinateBasis (d := d))).det) :
    letI := nuisanceProjectionInstance paths
    (efficientInformationMatrix Sθ paths.nuisanceTangent
      (coordinateBasis (d := d))).PosDef := by
  letI := nuisanceProjectionInstance paths
  let I := efficientInformationMatrix Sθ paths.nuisanceTangent
    (coordinateBasis (d := d))
  have hpsd : I.PosSemidef := efficientInformationMatrix_posSemidef _ _ _
  exact hpsd.posDef_iff_isUnit.mpr (Matrix.isUnit_iff_isUnit_det I |>.mpr hdet)

/-- Nonsingular efficient information derives the chosen vector
derivative and the candidate vector EIF, without caller-supplied projection,
BASE differentiability, membership, Gram, or derivative identities. -/
theorem chosenPathwise_and_eif_from_vectorPaths
    (Sθ : OrdinaryScore P (EuclideanSpace ℝ (Fin d)))
    {ψ : Measure Ω → EuclideanSpace ℝ (Fin d)}
    (paths : VectorPaths25_26 Sθ ψ)
    (hdet : letI := nuisanceProjectionInstance paths
      IsUnit (efficientInformationMatrix Sθ paths.nuisanceTangent
        (coordinateBasis (d := d))).det) :
    letI := nuisanceProjectionInstance paths
    ∃ hpd : ChosenPathwiseDifferentiableAtVec paths,
      IsEfficientInfluenceFunction_vec hpd.derivative
        (candidateVecEIF Sθ paths.nuisanceTangent (coordinateBasis (d := d))) := by
  classical
  letI := nuisanceProjectionInstance paths
  let e := coordinateBasis (d := d)
  let I := efficientInformationMatrix Sθ paths.nuisanceTangent e
  let cand := candidateVecEIF Sθ paths.nuisanceTangent e
  have hPD : I.PosDef :=
    efficientInformation_posDef_of_isUnit_det Sθ paths hdet
  have hnuis_le : paths.nuisanceTangent ≤ paths.totalTangent := by
    apply Submodule.topologicalClosure_minimal
    · apply Submodule.span_le.mpr
      intro g hg
      simpa using paths.selectedScore_mem (0 : EuclideanSpace ℝ (Fin d)) g hg
    · exact Submodule.isClosed_topologicalClosure _
  have heff_mem (a : EuclideanSpace ℝ (Fin d)) :
      efficientScore Sθ paths.nuisanceTangent a ∈ paths.totalTangent := by
    apply paths.totalTangent.sub_mem
    · simpa using paths.selectedScore_mem a 0 paths.nuisance_zero_mem
    · exact hnuis_le (paths.nuisanceTangent.starProjection_apply_mem (Sθ a))
  have hcand_mem (j : Fin d) : cand j ∈ paths.totalTangent := by
    apply Submodule.sum_mem
    intro k _
    exact paths.totalTangent.smul_mem _ (heff_mem (e k))
  have ha_expand (a : EuclideanSpace ℝ (Fin d)) :
      a = ∑ j, a j • e j := by
    apply PiLp.ext
    intro j
    simp [e, coordinateBasis, Pi.single_apply]
  have heff_expand (a : EuclideanSpace ℝ (Fin d)) :
      efficientScore Sθ paths.nuisanceTangent a =
        ∑ j, a j • efficientScore Sθ paths.nuisanceTangent (e j) := by
    calc
      _ = efficientScore Sθ paths.nuisanceTangent (∑ j, a j • e j) :=
        congrArg _ (ha_expand a)
      _ = _ := by
        simp only [efficientScore, map_sum, map_smul, smul_sub,
          Finset.sum_sub_distrib]
  have hcand_inner (a : EuclideanSpace ℝ (Fin d))
      (g : ↥(L2ZeroMean P)) (hg : g ∈ paths.nuisanceSet) (j : Fin d) :
      ⟪cand j, Sθ a + g⟫_ℝ = a j := by
    have hg_nuis : g ∈ paths.nuisanceTangent := by
      apply (Submodule.span ℝ paths.nuisanceSet).le_topologicalClosure
      exact Submodule.subset_span hg
    have heff_inner (k : Fin d) :
        ⟪efficientScore Sθ paths.nuisanceTangent (e k), Sθ a + g⟫_ℝ =
          ∑ l, I k l * a l := by
      rw [inner_add_right,
        efficientScore_inner_nuisance_eq_zero Sθ paths.nuisanceTangent
          (e k) (g := g) hg_nuis,
        add_zero, efficientScore_inner_ordinary_eq_self,
        heff_expand a, inner_sum]
      simp only [I, efficientInformationMatrix_apply]
      apply Finset.sum_congr rfl
      intro l _
      rw [real_inner_comm, real_inner_smul_left, real_inner_comm]
      exact mul_comm _ _
    change ⟪∑ k, I⁻¹ j k • efficientScore Sθ paths.nuisanceTangent (e k),
      Sθ a + g⟫_ℝ = a j
    rw [sum_inner]
    simp_rw [real_inner_smul_left, heff_inner]
    change Matrix.mulVec (I⁻¹) (Matrix.mulVec I (fun l => a l)) j = a j
    rw [Matrix.mulVec_mulVec, Matrix.nonsing_inv_mul _ hdet,
      Matrix.one_mulVec]
  let D : paths.totalTangent →L[ℝ] EuclideanSpace ℝ (Fin d) :=
    (EuclideanSpace.equiv (Fin d) ℝ).symm.toContinuousLinearMap.comp
      (ContinuousLinearMap.pi fun j =>
        (innerSL ℝ (cand j)).comp paths.totalTangent.subtypeL)
  have hD_selected (a : EuclideanSpace ℝ (Fin d))
      (g : ↥(L2ZeroMean P)) (hg : g ∈ paths.nuisanceSet) :
      D ⟨Sθ a + g, paths.selectedScore_mem a g hg⟩ = a := by
    apply PiLp.ext
    intro j
    exact hcand_inner a g hg j
  let hpd : ChosenPathwiseDifferentiableAtVec paths :=
    { derivative := D
      derivative_spec := fun a g hg => by
        rw [hD_selected a g hg]
        exact paths.quotient a g hg
      derivative_selectedScore := hD_selected }
  refine ⟨hpd, eif_from_efficientScore_vec Sθ paths.nuisanceTangent e
    paths.totalTangent hpd.derivative hPD hcand_mem ?_⟩
  intro j g
  rfl

end AsymptoticStatistics.StrictModel.EfficientScoreChosenPathsVec
