import Mathlib.Combinatorics.SetFamily.Shatter
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Algebra.Ring.GeomSum
import Mathlib.Data.Finset.Preimage
import Mathlib.Data.Nat.Choose.Bounds
import Mathlib.Data.Real.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Real

/-!
# Vapnik–Chervonenkis classes and finite traces

Structural definitions and the finite-trace/Sauer bridge used by van der
Vaart §19.2. The book's VC index is the least cardinality that cannot be
shattered, hence one more than the usual maximal shattered cardinality.

Reference: van der Vaart, *Asymptotic Statistics*, §19.2, pp.274–275.
-/

namespace AsymptoticStatistics.EmpiricalProcess

variable {α Ω : Type*}

/-- The strict subgraph of `f`, with the convention used in vdV's examples:
`(x,t)` belongs exactly when `t < f x`.

Edge behavior: strictness excludes points on the graph. This convention is
kept explicit because changing `<` to `≤` can alter exact finite traces. -/
def strictSubgraph (f : Ω → ℝ) : Set (Ω × ℝ) :=
  {p | p.2 < f p.1}

/-- The family of strict subgraphs generated by a function class.

Edge behavior: an empty function class generates the empty set family. -/
def strictSubgraphFamily (F : Set (Ω → ℝ)) : Set (Set (Ω × ℝ)) :=
  {A | ∃ f ∈ F, A = strictSubgraph f}

/-- The finite trace of a possibly infinite set family on a finite sample.

It contains precisely the subsets of `s` picked out by intersections with
members of `𝒜`. Edge behavior: the trace of an empty family is empty. -/
noncomputable def finiteTrace (𝒜 : Set (Set α)) (s : Finset α) : Finset (Finset α) := by
  classical
  exact s.powerset.filter fun t => ∃ A ∈ 𝒜, ∀ x ∈ s, (x ∈ t ↔ x ∈ A)

/-- A set family shatters `s` when it realizes every subset of `s` as a trace.

This is the infinite-family counterpart of Mathlib's `Finset.Shatters`. -/
noncomputable def SetFamilyShatters (𝒜 : Set (Set α)) (s : Finset α) : Prop := by
  classical
  exact ∀ t, t ⊆ s → ∃ A ∈ 𝒜, ∀ x ∈ s, (x ∈ t ↔ x ∈ A)

/-- `VCIndexLE 𝒜 V` says the book VC index is at most `V`: no finite set of
cardinality at least `V` is shattered.

Thus `V` is the least forbidden size, equal to the usual VC dimension plus
one when the maximum shattered size exists. Edge behavior: `V = 0` forces even
the empty set not to be shattered. -/
noncomputable def VCIndexLE (𝒜 : Set (Set α)) (V : ℕ) : Prop := by
  exact ∀ s : Finset α, V ≤ s.card → ¬ SetFamilyShatters 𝒜 s

/-- The pure combinatorial assertion that the strict-subgraph family has book
VC index at most `V`. No measurability is included. -/
noncomputable def HasVCSubgraphIndexLE (F : Set (Ω → ℝ)) (V : ℕ) : Prop :=
  @VCIndexLE (Ω × ℝ) (strictSubgraphFamily F) V

/-- A book-facing VC-subgraph class of real measurable functions.

Constitutive (vdV §19.2 p.275): a VC class of functions consists of measurable
functions and its subgraph family has finite VC index. The VC property does not
imply the separate suitable-measurability condition used by Theorems 19.13 and
19.14. -/
noncomputable def IsVCSubgraphClass [MeasurableSpace Ω]
    (F : Set (Ω → ℝ)) (V : ℕ) : Prop :=
  (∀ f ∈ F, Measurable f) ∧ HasVCSubgraphIndexLE F V

private def sampleEmbedding (s : Finset α) : ↑s ↪ α :=
  ⟨Subtype.val, Subtype.coe_injective⟩

private noncomputable def restrictFinset (s t : Finset α) : Finset ↑s :=
  t.preimage (sampleEmbedding s) (sampleEmbedding s).injective.injOn

@[simp]
private theorem mem_restrictFinset {s t : Finset α} {x : ↑s} :
    x ∈ restrictFinset s t ↔ x.1 ∈ t := by
  classical
  simp [restrictFinset, sampleEmbedding]

private theorem map_restrictFinset_eq {s t : Finset α} (ht : t ⊆ s) :
    (restrictFinset s t).map (sampleEmbedding s) = t := by
  classical
  ext x
  constructor
  · simp only [Finset.mem_map, mem_restrictFinset]
    rintro ⟨y, hy, rfl⟩
    exact hy
  · intro hx
    refine Finset.mem_map.mpr ⟨⟨x, ht hx⟩, ?_, rfl⟩
    exact mem_restrictFinset.mpr hx

private noncomputable def restrictFamily
    (T : Finset (Finset α)) (s : Finset α) : Finset (Finset ↑s) := by
  classical
  exact T.image (restrictFinset s)

private theorem card_restrictFamily
    {T : Finset (Finset α)} {s : Finset α}
    (hT : ∀ t ∈ T, t ⊆ s) :
    (restrictFamily T s).card = T.card := by
  classical
  change (T.image (restrictFinset s)).card = T.card
  apply Finset.card_image_of_injOn
  intro t ht u hu htu
  ext x
  constructor
  · intro hxt
    let y : ↑s := ⟨x, hT t ht hxt⟩
    have hy : y ∈ restrictFinset s t := by
      exact mem_restrictFinset.mpr hxt
    rw [htu] at hy
    exact mem_restrictFinset.mp hy
  · intro hxu
    let y : ↑s := ⟨x, hT u hu hxu⟩
    have hy : y ∈ restrictFinset s u := by
      exact mem_restrictFinset.mpr hxu
    rw [← htu] at hy
    exact mem_restrictFinset.mp hy

private theorem shatters_of_restrictFamily_shatters
    [DecidableEq α] {T : Finset (Finset α)} {s : Finset α}
    (hT : ∀ t ∈ T, t ⊆ s) {u : Finset ↑s}
    (hu : (restrictFamily T s).Shatters u) :
    T.Shatters (u.map (sampleEmbedding s)) := by
  classical
  intro r hr
  have humap : u.map (sampleEmbedding s) ⊆ s := by
    intro x hx
    obtain ⟨y, _, rfl⟩ := Finset.mem_map.mp hx
    exact y.2
  have hrsub : r ⊆ s := hr.trans humap
  have hr' : restrictFinset s r ⊆ u := by
    intro x hx
    have hxmap : x.1 ∈ r := mem_restrictFinset.mp hx
    have hxumap : x.1 ∈ u.map (sampleEmbedding s) := hr hxmap
    simpa [sampleEmbedding] using hxumap
  obtain ⟨v, hv, huv⟩ := hu hr'
  simp only [restrictFamily, Finset.mem_image] at hv
  obtain ⟨t, ht, rfl⟩ := hv
  refine ⟨t, ht, ?_⟩
  have hmap := congrArg (Finset.map (sampleEmbedding s)) huv
  simpa only [Finset.map_inter, map_restrictFinset_eq (hT t ht),
    map_restrictFinset_eq hrsub] using hmap

/-- The project infinite-family shattering predicate is equivalent to
Mathlib shattering for the concrete finite trace. -/
theorem setFamilyShatters_iff_finiteTrace_shatters
    [DecidableEq α] (𝒜 : Set (Set α)) (s : Finset α) :
    SetFamilyShatters 𝒜 s ↔ (finiteTrace 𝒜 s).Shatters s := by
  classical
  constructor
  · intro h t ht
    obtain ⟨A, hA, hAt⟩ := h t ht
    refine ⟨t, ?_, Finset.inter_eq_right.mpr ht⟩
    simp only [finiteTrace, Finset.mem_filter, Finset.mem_powerset]
    exact ⟨ht, A, hA, hAt⟩
  · intro h t ht
    obtain ⟨u, hu, hsu⟩ := h ht
    simp only [finiteTrace, Finset.mem_filter, Finset.mem_powerset] at hu
    obtain ⟨_, A, hA, huA⟩ := hu
    refine ⟨A, hA, fun x hx ↦ ?_⟩
    have hxtu : x ∈ t ↔ x ∈ u := by
      rw [← hsu]
      simp only [Finset.mem_inter, hx, true_and]
    exact hxtu.trans (huA x hx)

/-- Every member of a finite trace is a subset of the sampled finset. -/
theorem mem_finiteTrace_subset {𝒜 : Set (Set α)} {s t : Finset α}
    (ht : t ∈ finiteTrace 𝒜 s) : t ⊆ s := by
  classical
  simp only [finiteTrace, Finset.mem_filter, Finset.mem_powerset] at ht
  exact ht.1

private theorem setFamilyShatters_of_finiteTrace_shatters
    [DecidableEq α] {𝒜 : Set (Set α)} {s u : Finset α} (hus : u ⊆ s)
    (hu : (finiteTrace 𝒜 s).Shatters u) : SetFamilyShatters 𝒜 u := by
  intro t ht
  obtain ⟨v, hv, huv⟩ := hu ht
  simp only [finiteTrace, Finset.mem_filter, Finset.mem_powerset] at hv
  obtain ⟨_, A, hA, hvA⟩ := hv
  refine ⟨A, hA, fun x hx ↦ ?_⟩
  have hxtv : x ∈ t ↔ x ∈ v := by
    rw [← huv]
    simp only [Finset.mem_inter, hx, true_and]
  exact hxtv.trans (hvA x (hus hx))

/-- Sauer's trace bound in the book-index convention.

If the smallest forbidden shattered size is at most `V`, the number of traces
on `n` points is at most `∑_{j < V} choose(n,j)`. -/
theorem sauer_shelah_finiteTrace_bound
    {𝒜 : Set (Set α)} {V : ℕ} (hV : VCIndexLE 𝒜 V) (s : Finset α) :
    (finiteTrace 𝒜 s).card ≤ ∑ j ∈ Finset.range V, s.card.choose j := by
  classical
  let T := finiteTrace 𝒜 s
  have hT : ∀ t ∈ T, t ⊆ s := by
    intro t ht
    exact mem_finiteTrace_subset ht
  by_cases hV0 : V = 0
  · subst V
    have hTempty : T = ∅ := by
      apply Finset.not_nonempty_iff_eq_empty.mp
      rintro ⟨t, ht⟩
      have hsh : T.Shatters ∅ := Finset.shatters_empty.mpr ⟨t, ht⟩
      exact hV ∅ (by simp) (setFamilyShatters_of_finiteTrace_shatters (by simp) hsh)
    simp [T, hTempty]
  · let B := restrictFamily T s
    have hcard : B.card = T.card := card_restrictFamily hT
    have hvc : B.vcDim < V := by
      rw [Finset.vcDim, Finset.sup_lt_iff (Nat.zero_lt_of_ne_zero hV0)]
      intro u hu
      have hush : B.Shatters u := Finset.mem_shatterer.mp hu
      have hTsh : T.Shatters (u.map (sampleEmbedding s)) :=
        shatters_of_restrictFamily_shatters hT hush
      have hAsh : SetFamilyShatters 𝒜 (u.map (sampleEmbedding s)) :=
        setFamilyShatters_of_finiteTrace_shatters
          (by
            intro x hx
            obtain ⟨y, _, rfl⟩ := Finset.mem_map.mp hx
            exact y.2)
          hTsh
      by_contra hnot
      exact hV (u.map (sampleEmbedding s))
        (by simpa only [Finset.card_map] using Nat.le_of_not_gt hnot) hAsh
    calc
      (finiteTrace 𝒜 s).card = B.card := by simpa [T] using hcard.symm
      _ ≤ B.shatterer.card := Finset.card_le_card_shatterer B
      _ ≤ ∑ j ∈ Finset.Iic B.vcDim, (Fintype.card ↑s).choose j :=
        Finset.card_shatterer_le_sum_vcDim
      _ = ∑ j ∈ Finset.Iic B.vcDim, s.card.choose j := by
        simp only [Fintype.card_coe]
      _ ≤ ∑ j ∈ Finset.range V, s.card.choose j := by
        apply Finset.sum_le_sum_of_subset_of_nonneg
        · intro j hj
          simp only [Finset.mem_Iic] at hj
          exact Finset.mem_range.mpr (lt_of_le_of_lt hj hvc)
        · simp

/-- Polynomial trace-growth basis following from Sauer's bound.

The deliberately coarse exponent `V` is sufficient for entropy applications;
the sharper book order is `O(n^(V-1))`. -/
theorem finiteTrace_card_le_polynomial
    {𝒜 : Set (Set α)} {V : ℕ} (hV : VCIndexLE 𝒜 V) (s : Finset α) :
    (finiteTrace 𝒜 s).card ≤ (s.card + 1) ^ V := by
  calc
    (finiteTrace 𝒜 s).card ≤ ∑ j ∈ Finset.range V, s.card.choose j :=
      sauer_shelah_finiteTrace_bound hV s
    _ ≤ ∑ j ∈ Finset.range V, s.card ^ j := by
      exact Finset.sum_le_sum fun j _ ↦ Nat.choose_le_pow s.card j
    _ ≤ (s.card + 1) ^ V := by
      by_cases hs0 : s.card = 0
      · simp only [hs0, zero_geom_sum, zero_add, one_pow]
        split <;> simp
      · rw [← geom_sum_mul_add s.card V]
        calc
          ∑ j ∈ Finset.range V, s.card ^ j ≤
              ∑ j ∈ Finset.range V, (s.card + 1) ^ j := by
            exact Finset.sum_le_sum fun j _ ↦
              Nat.pow_le_pow_left (Nat.le_add_right s.card 1) j
          _ =
              (∑ j ∈ Finset.range V, (s.card + 1) ^ j) * 1 := by simp
          _ ≤ (∑ j ∈ Finset.range V, (s.card + 1) ^ j) * s.card := by
            exact Nat.mul_le_mul_left _ (Nat.one_le_iff_ne_zero.mpr hs0)
          _ ≤ (∑ j ∈ Finset.range V, (s.card + 1) ^ j) * s.card + 1 :=
            Nat.le_add_right _ _

/-- Shattering is monotone under restriction of the sampled finite set. -/
theorem SetFamilyShatters.mono {𝒜 : Set (Set α)} {s t : Finset α}
    (hs : SetFamilyShatters 𝒜 s) (hts : t ⊆ s) :
    SetFamilyShatters 𝒜 t := by
  intro u hu
  obtain ⟨A, hA, huA⟩ := hs u (hu.trans hts)
  exact ⟨A, hA, fun x hx ↦ huA x (hts hx)⟩

/-- Enlarging the allowed book index weakens the VC-index bound. -/
theorem VCIndexLE.mono {𝒜 : Set (Set α)} {V W : ℕ}
    (hV : VCIndexLE 𝒜 V) (hVW : V ≤ W) : VCIndexLE 𝒜 W := by
  intro s hs
  exact hV s (hVW.trans hs)

end AsymptoticStatistics.EmpiricalProcess
