import Mathlib.MeasureTheory.Function.ConditionalExpectation.Basic
import Mathlib.MeasureTheory.Constructions.Pi
import Mathlib.Analysis.InnerProductSpace.PiL2
import Mathlib.Analysis.Normed.Lp.MeasurableSpace

/-!
# Longitudinal data — subject records, marginal mean models, GEE

The longitudinal slice's data model. One **subject record** holds `m` visits: visit times,
per-visit covariates, and the response vector — finite and vector-valued (no continuous
trajectories: functional-data models are out of scope by design; ragged per-subject visit
counts are a documented deviation, fixed `m` here).

* `LongitudinalRecord p m` — the subject record;
* `covariateSigma p m` — the σ-algebra generated by `(times, x)` (what "given the
  covariates" means);
* `IsMarginalMeanModel Q μfun β` — the **marginal mean model as a conditional-moment
  constraint on the law**: `E[yⱼ ∣ times, x] = μ(β; timesⱼ, xⱼ)` for every visit `j`. This is
  a partially specified (constraint) model in the sense of `Constraint.Defs`: nothing else
  about `Q` is restricted;
* `GEESpec p m q Θβ` — the user's estimating-equation specification: mean function, Jacobian
  `D = ∂μ/∂β` (supplied, not derived), and working covariance `V`. These three choices
  *define* the GEE — constitutive fields (Liang–Zeger Eq. (6));
* `geeWeight`, `geeResidual`, `geeScore` — the weight matrix `Dᵀ V⁻¹`, the residual
  `y − μ(β)`, and the estimating function `U(β) = Dᵀ V⁻¹ (y − μ(β))` (coordinates in
  `Fin q → ℝ`).

**Reference.** K.-Y. Liang and S. L. Zeger, "Longitudinal data analysis using generalized
linear models," *Biometrika* **73** (1986), 13–22, §2, Eq. (6) (`LZ86 §2`); G. M.
Fitzmaurice, N. M. Laird, and J. H. Ware, *Applied Longitudinal Analysis*, 2nd ed., Wiley,
2011, Ch. 13 (marginal models and GEE) (verify §) (`FLW Ch. 13`).

**Proof formalization notes.** Laptop-only data model — definitions only. The record carries
its σ-algebra by `comap` of the triple `(times, x, y)` (the `MARObs` idiom); `covariateSigma`
is the sub-σ-algebra generated by the first two components, and the mean model is stated with
Mathlib's `condExp` against it. The working covariance enters through `Matrix.inv` — junk
(zero matrix) when singular; theorems that need invertibility state it. `V` is a function of
the visit data only (covariate-measurable by construction), which is exactly what makes the
GEE unbiased (`Longitudinal.GEE`).

**Bibliographic comments.** Estimating functions: V. P. Godambe, *Ann. Math. Statist.* **31**
(1960), 1208–1211 (`God60`). GEE for longitudinal data: Liang–Zeger (1986); the working-
covariance vocabulary is theirs. The marginal-vs-mixed model distinction: FLW Ch. 13.
-/

open MeasureTheory Matrix

namespace StatLean.StatisticalModels.Longitudinal

/-- A **longitudinal subject record** with `m` visits and `p`-dimensional per-visit
covariates: visit times, covariates, responses (`LZ86 §2`; FLW Ch. 13). Finite and
vector-valued by design (no trajectories). -/
structure LongitudinalRecord (p m : ℕ) where
  /-- Visit times `t₁, …, t_m`. -/
  times : Fin m → ℝ
  /-- Per-visit covariate vectors `x₁, …, x_m`. -/
  x : Fin m → EuclideanSpace ℝ (Fin p)
  /-- The response vector `(y₁, …, y_m)`. -/
  y : EuclideanSpace ℝ (Fin m)

/-- The record's ambient σ-algebra: `comap` of the component triple (the `MARObs` idiom). -/
instance (p m : ℕ) : MeasurableSpace (LongitudinalRecord p m) :=
  MeasurableSpace.comap (fun r => (r.times, r.x, r.y)) inferInstance

/-- The **covariate σ-algebra**: generated by `(times, x)` — conditioning "given the
covariates" means conditioning on this sub-σ-algebra. -/
def covariateSigma (p m : ℕ) : MeasurableSpace (LongitudinalRecord p m) :=
  MeasurableSpace.comap (fun r => (r.times, r.x)) inferInstance

/-- The **marginal mean model** as a conditional-moment constraint on the law `Q`
(`LZ86 §2` Eq. (2); FLW Ch. 13): for every visit, the conditional mean of the response given
the covariates is the specified mean function. Nothing else about `Q` is restricted — a
partially specified model in the sense of `Constraint.Defs`. -/
def IsMarginalMeanModel {p m : ℕ} {Θβ : Type*} (Q : Measure (LongitudinalRecord p m))
    (μfun : Θβ → ℝ × EuclideanSpace ℝ (Fin p) → ℝ) (β : Θβ) : Prop :=
  ∀ j : Fin m,
    Q[fun r => r.y j|covariateSigma p m] =ᵐ[Q] fun r => μfun β (r.times j, r.x j)

/-- The **GEE specification** (`LZ86 §2` Eq. (6)): the mean function, the user-supplied
Jacobian `D = ∂μ/∂β`, and the working covariance `V`, each a function of the visit data.
These choices *define* the estimating equation. -/
structure GEESpec (p m q : ℕ) (Θβ : Type*) where
  /-- Constitutive (LZ86 Eq. (2)): the marginal mean function `μ(β; t, x)`. -/
  μfun : Θβ → ℝ × EuclideanSpace ℝ (Fin p) → ℝ
  /-- Constitutive (LZ86 Eq. (6)): the Jacobian `Dⱼₖ = ∂μⱼ/∂βₖ`, supplied — the GEE is
  defined by the user's `D`, not by a derived derivative. -/
  Dmat : Θβ → (Fin m → ℝ) → (Fin m → EuclideanSpace ℝ (Fin p)) → Matrix (Fin m) (Fin q) ℝ
  /-- Constitutive (LZ86 Eq. (6)): the working covariance `V` of the response given the
  covariates — a modeling choice, not required correct. -/
  Vmat : (Fin m → ℝ) → (Fin m → EuclideanSpace ℝ (Fin p)) → Matrix (Fin m) (Fin m) ℝ

namespace GEESpec

variable {p m q : ℕ} {Θβ : Type*}

/-- The GEE weight matrix `Dᵀ V⁻¹` as a function of the visit data (junk when `V` is
singular; invertibility is a hypothesis where needed). -/
noncomputable def geeWeight (S : GEESpec p m q Θβ) (β : Θβ) (t : Fin m → ℝ)
    (xv : Fin m → EuclideanSpace ℝ (Fin p)) : Matrix (Fin q) (Fin m) ℝ :=
  (S.Dmat β t xv)ᵀ * (S.Vmat t xv)⁻¹

/-- The residual vector `y − μ(β)` of a record. -/
noncomputable def geeResidual (S : GEESpec p m q Θβ) (β : Θβ)
    (r : LongitudinalRecord p m) : Fin m → ℝ :=
  fun j => r.y j - S.μfun β (r.times j, r.x j)

/-- The **GEE estimating function** `U(β) = Dᵀ V⁻¹ (y − μ(β))` of one record
(`LZ86 §2` Eq. (6)), in plain coordinates. -/
noncomputable def geeScore (S : GEESpec p m q Θβ) (β : Θβ)
    (r : LongitudinalRecord p m) : Fin q → ℝ :=
  (S.geeWeight β r.times r.x).mulVec (S.geeResidual β r)

end GEESpec

end StatLean.StatisticalModels.Longitudinal
