import StatLean.AsymptoticStatistics.Core.EIF
import StatLean.AsymptoticStatistics.ForMathlib.CondExpL2
import Mathlib.MeasureTheory.Function.ConditionalExpectation.CondexpL2
import Mathlib.MeasureTheory.Measure.Map

/-!
# Information-loss operator (observed-data score via conditional expectation)

In a coarsening (missing-data) model one observes not the full datum but a
coarsened summary, recorded by a measurement map $M : \Omega_{\mathrm{full}}
\to \Omega_{\mathrm{obs}}$. The full-data model induces the observed-data
distribution $P_{\mathrm{obs}} = P_{\mathrm{full}} \circ M^{-1}$ (the pushforward
of $P_{\mathrm{full}}$ under $M$). The **information-loss operator** sends a
full-data score $g$ to the observed-data score obtained by taking the
conditional expectation of $g$ given the observed data, i.e. given the
sub-$\sigma$-algebra $M^{-1}(\Sigma_{\mathrm{obs}})$ generated by $M$:
$$ g \;\longmapsto\; E_{P_{\mathrm{full}}}\!\bigl[\, g \mid M^{-1}
(\Sigma_{\mathrm{obs}})\,\bigr]. $$
Because this conditional expectation is $M^{-1}(\Sigma_{\mathrm{obs}})$-measurable,
the Doob–Dynkin factorization identifies it with a genuine function of the
observed data, giving a bounded linear map between the mean-zero square-integrable
spaces $L^2_0(P_{\mathrm{full}}) \to L^2_0(P_{\mathrm{obs}})$.

In Lean this is realized via `condExpL2` (the orthogonal projection onto the
$L^2$ subspace of $M^{-1}(\Sigma_{\mathrm{obs}})$-measurable functions) composed
with the Doob $L^2$ isomorphism `doobL2Equiv`, which transports an
$M^{-1}(\Sigma_{\mathrm{obs}})$-measurable element of $L^2(P_{\mathrm{full}})$ to
the corresponding element of $L^2(P_{\mathrm{obs}})$. The two measures involved
are $P_{\mathrm{full}}$ on $\Omega_{\mathrm{full}}$ and
$P_{\mathrm{obs}} = P_{\mathrm{full}}.\mathrm{map}\,M$ on $\Omega_{\mathrm{obs}}$.

**Reference.** A. W. van der Vaart, *Asymptotic Statistics*, Cambridge Series in
Statistical and Probabilistic Mathematics, Cambridge University Press, 1998,
Chapter 25 (Semiparametric Models), §25.5 (Score and Information Operators), the
*Information Loss Models* subsection (§25.5.2), with related material in §25.6
(Missing and Coarsening at Random), Lemma 25.34.

**Proof formalization notes.** The information-loss operator bridges
`↥(L²₀(P_full)) →L[ℝ] ↥(L²₀(P_obs))` via `condExpL2` (conditional expectation as
an orthogonal $L^2$ projection onto $M^{-1}(\Sigma_{\mathrm{obs}})$-measurable
functions) composed with the Doob $L^2$ isomorphism `doobL2Equiv`. Downstream
theorems (lem:25.34, thm:25.40, lem:25.41, cor:25.42) reference the operator and
the Doob equivalence's defining identity `doobL2Equiv_comp_apply` by name.

**Bibliographic comments.** The systematic theory of observed-data scores under
coarsening, and the Coarsening At Random (CAR) condition that lets the observed
score be obtained as a conditional expectation of the full-data score, originates
with R. D. Gill, M. J. van der Laan, and J. M. Robins, "Coarsening at random:
characterizations, conjectures, counter-examples," in *Proceedings of the First
Seattle Symposium in Biostatistics: Survival Analysis* (D. Y. Lin and T. R.
Fleming, eds.), Lecture Notes in Statistics 123, Springer, 1997, pp. 255–294.
That work generalizes the missing-at-random (MAR) notion of D. B. Rubin,
"Inference and missing data," *Biometrika* 63 (1976), 581–592, to general
coarsening mechanisms and characterizes when the coarsening is ancillary for the
full-data parameter. Van der Vaart's §25.5.2 (Information Loss Models) presents the
resulting information-loss operator as a Hilbert-space projection; the
conditional-expectation form formalized here synthesizes that line of work.
-/

open MeasureTheory Filter Topology
open scoped InnerProductSpace ENNReal

set_option linter.dupNamespace false

namespace AsymptoticStatistics.Operators.InformationLoss

open AsymptoticStatistics.Core.Hilbert
open AsymptoticStatistics.ForMathlib.CondExpL2

variable {Ω_full Ω_obs : Type*}
  [MeasurableSpace Ω_full] [MeasurableSpace Ω_obs]
end AsymptoticStatistics.Operators.InformationLoss
